// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ICD-10 Mutual Exclusion Rules — South African Healthcare Claims
// WHO ICD-10 (NOT US ICD-10-CM) — ~250 rules across 11 clinical areas
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import type { CodePairViolation } from "./types";

export const ICD10_EXCLUSIONS: CodePairViolation[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 1. DIABETES TYPE EXCLUSIONS (~15)
  // E10 = Type 1, E11 = Type 2, E13 = Other specified, E14 = Unspecified
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "E10",
    code2: "E11",
    type: "mutually_exclusive",
    reason: "Type 1 diabetes mellitus (E10) and Type 2 diabetes mellitus (E11) are mutually exclusive diagnoses. A patient has one or the other based on pathophysiology — autoimmune beta-cell destruction vs insulin resistance. Coding both simultaneously is a classification error.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes (CDL 2)",
    category: "icd10_exclusion",
  },
  {
    code1: "E10",
    code2: "E13",
    type: "mutually_exclusive",
    reason: "Type 1 diabetes (E10) and other specified diabetes (E13) cannot coexist. E13 covers secondary causes such as pancreatectomy or drug-induced diabetes, which are distinct from the autoimmune aetiology of Type 1.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "E10",
    code2: "E14",
    type: "mutually_exclusive",
    reason: "Type 1 diabetes (E10) is a specific diagnosis; unspecified diabetes (E14) should never appear alongside it. If the type is known to be Type 1, E14 is redundant and incorrect.",
    source: "WHO ICD-10 coding conventions; BHF coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E11",
    code2: "E13",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes (E11) and other specified diabetes (E13) represent different aetiologies. A patient should be coded with the most accurate type — not both.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E11",
    code2: "E14",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes (E11) is a specific diagnosis; unspecified diabetes (E14) is redundant when the type is known. Claims should use the most specific code available.",
    source: "WHO ICD-10 coding conventions; BHF coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E13",
    code2: "E14",
    type: "mutually_exclusive",
    reason: "Other specified diabetes (E13) is itself a specific classification; unspecified diabetes (E14) should not appear alongside it as it adds no clinical information.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.0",
    code2: "E11.0",
    type: "mutually_exclusive",
    reason: "Diabetic coma in Type 1 (E10.0) and Type 2 (E11.0) cannot coexist. The patient has one diabetes type; the coma complication attaches to that specific type.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.1",
    code2: "E11.1",
    type: "mutually_exclusive",
    reason: "Diabetic ketoacidosis in Type 1 (E10.1) and Type 2 (E11.1) cannot coexist on the same claim. Ketoacidosis occurs in one diabetes type per patient.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.2",
    code2: "E11.2",
    type: "mutually_exclusive",
    reason: "Diabetic renal complications in Type 1 (E10.2) vs Type 2 (E11.2) — only one diabetes type applies per patient. Coding both implies contradictory diagnoses.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.3",
    code2: "E11.3",
    type: "mutually_exclusive",
    reason: "Diabetic ophthalmic complications in Type 1 (E10.3) vs Type 2 (E11.3) are mutually exclusive. Retinopathy is coded under the patient's actual diabetes type.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.4",
    code2: "E11.4",
    type: "mutually_exclusive",
    reason: "Diabetic neurological complications in Type 1 (E10.4) vs Type 2 (E11.4) — neuropathy must be coded under the correct diabetes type, not both.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.5",
    code2: "E11.5",
    type: "mutually_exclusive",
    reason: "Diabetic peripheral circulatory complications in Type 1 (E10.5) vs Type 2 (E11.5) cannot coexist. The vascular complication is attributed to one diabetes type only.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.6",
    code2: "E11.6",
    type: "mutually_exclusive",
    reason: "Diabetic arthropathy and other specified complications in Type 1 (E10.6) vs Type 2 (E11.6) are mutually exclusive by diabetes type.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.7",
    code2: "E11.7",
    type: "mutually_exclusive",
    reason: "Multiple diabetic complications in Type 1 (E10.7) vs Type 2 (E11.7) — the multiple complications code must correspond to the patient's single diabetes type.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E10.9",
    code2: "E11.9",
    type: "mutually_exclusive",
    reason: "Type 1 diabetes without complications (E10.9) and Type 2 diabetes without complications (E11.9) are mutually exclusive — a patient cannot have both diabetes types simultaneously.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. HYPERTENSION TYPE EXCLUSIONS (~15)
  // I10 = Essential HTN, I11 = Hypertensive heart, I12 = Hypertensive renal,
  // I13 = Hypertensive heart + renal, I15 = Secondary HTN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "I10",
    code2: "I11",
    type: "mutually_exclusive",
    reason: "Essential hypertension (I10) is subsumed by hypertensive heart disease (I11). When cardiac involvement is present, I11 replaces I10 — both should not appear on the same claim.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for hypertension (CDL 14)",
    category: "icd10_exclusion",
  },
  {
    code1: "I10",
    code2: "I12",
    type: "mutually_exclusive",
    reason: "Essential hypertension (I10) is subsumed by hypertensive renal disease (I12). When renal involvement from hypertension is documented, I12 replaces I10.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for hypertension",
    category: "icd10_exclusion",
  },
  {
    code1: "I10",
    code2: "I13",
    type: "mutually_exclusive",
    reason: "Essential hypertension (I10) is subsumed by hypertensive heart and renal disease (I13). I13 encompasses the base hypertension diagnosis along with both organ complications.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for hypertension",
    category: "icd10_exclusion",
  },
  {
    code1: "I10",
    code2: "I15",
    type: "mutually_exclusive",
    reason: "Essential (primary) hypertension (I10) and secondary hypertension (I15) are mutually exclusive by definition. Hypertension is either idiopathic (I10) or secondary to an identifiable cause (I15).",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I11",
    code2: "I13",
    type: "mutually_exclusive",
    reason: "Hypertensive heart disease (I11) is subsumed by hypertensive heart and renal disease (I13). If both cardiac and renal involvement exist, only I13 should be coded.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I12",
    code2: "I13",
    type: "mutually_exclusive",
    reason: "Hypertensive renal disease (I12) is subsumed by hypertensive heart and renal disease (I13). If both organs are involved, I13 captures the full clinical picture.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I11",
    code2: "I15",
    type: "mutually_exclusive",
    reason: "Hypertensive heart disease (I11) implies essential hypertension with cardiac involvement, which is incompatible with secondary hypertension (I15). Secondary HTN with cardiac effects is coded differently.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I12",
    code2: "I15",
    type: "mutually_exclusive",
    reason: "Hypertensive renal disease (I12) implies essential hypertension causing renal damage, incompatible with secondary hypertension (I15) which has a different underlying cause.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I13",
    code2: "I15",
    type: "mutually_exclusive",
    reason: "Hypertensive heart and renal disease (I13) is an essential hypertension complication code. It cannot coexist with secondary hypertension (I15) which has a distinct aetiology.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I11.0",
    code2: "I13.0",
    type: "mutually_exclusive",
    reason: "Hypertensive heart disease with heart failure (I11.0) is subsumed by hypertensive heart and renal disease with heart failure (I13.0) when renal involvement is also present.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I11.9",
    code2: "I13.9",
    type: "mutually_exclusive",
    reason: "Hypertensive heart disease without heart failure (I11.9) is subsumed by I13.9 when renal disease is also documented. Use the combination code.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I12.0",
    code2: "I13.1",
    type: "mutually_exclusive",
    reason: "Hypertensive renal disease with renal failure (I12.0) is subsumed by hypertensive heart and renal disease with renal failure (I13.1) when cardiac involvement is documented.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I15.0",
    code2: "I15.1",
    type: "mutually_exclusive",
    reason: "Renovascular hypertension (I15.0) and hypertension secondary to other renal disorders (I15.1) represent different aetiologies of secondary hypertension. Only one cause should be coded as primary.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I15.0",
    code2: "I15.2",
    type: "mutually_exclusive",
    reason: "Renovascular hypertension (I15.0) and hypertension secondary to endocrine disorders (I15.2) have different underlying causes. Only the confirmed aetiology should be coded.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I11.0",
    code2: "I11.9",
    type: "mutually_exclusive",
    reason: "Hypertensive heart disease with heart failure (I11.0) and without heart failure (I11.9) are mutually exclusive — heart failure is either present or absent.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. RESPIRATORY EXCLUSIONS (~20)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "J12",
    code2: "J18",
    type: "mutually_exclusive",
    reason: "Viral pneumonia (J12) is a specific aetiological diagnosis. Unspecified pneumonia (J18) should not be coded alongside it — if the organism is identified, only the specific code applies.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J13",
    code2: "J18",
    type: "mutually_exclusive",
    reason: "Pneumococcal pneumonia (J13) identifies the causative organism. Unspecified pneumonia (J18) is redundant and should not be coded alongside the specific diagnosis.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J14",
    code2: "J18",
    type: "mutually_exclusive",
    reason: "Haemophilus influenzae pneumonia (J14) is organism-specific. Unspecified pneumonia (J18) must not accompany it — the specific code takes precedence.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J15",
    code2: "J18",
    type: "mutually_exclusive",
    reason: "Bacterial pneumonia, not elsewhere classified (J15), identifies a bacterial cause. Unspecified pneumonia (J18) is superseded by this specific code.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J15.0",
    code2: "J18.9",
    type: "mutually_exclusive",
    reason: "Klebsiella pneumonia (J15.0) is organism-specific. Pneumonia, unspecified (J18.9) adds no information and is contradictory when the pathogen is known.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J15.1",
    code2: "J18.9",
    type: "mutually_exclusive",
    reason: "Pseudomonas pneumonia (J15.1) is a specific bacterial diagnosis. Unspecified pneumonia (J18.9) should be replaced by the specific code, not coded alongside it.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J44",
    code2: "J45",
    type: "mutually_exclusive",
    reason: "COPD (J44) and asthma (J45) are distinct obstructive airway diseases with different pathophysiology. While asthma-COPD overlap exists, dual coding is flagged for review as schemes require documentation of overlap syndrome.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for COPD (CDL 4) and asthma (CDL 3)",
    category: "icd10_exclusion",
  },
  {
    code1: "J43",
    code2: "J44",
    type: "mutually_exclusive",
    reason: "Emphysema (J43) is a component of COPD (J44). J44 includes emphysema by definition — coding both is redundant. Use J44 with the appropriate subcategory.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J43.0",
    code2: "J43.1",
    type: "mutually_exclusive",
    reason: "MacLeod syndrome (J43.0) and panlobular emphysema (J43.1) are distinct emphysema subtypes. Only the confirmed subtype should be coded per encounter.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J43.1",
    code2: "J43.2",
    type: "mutually_exclusive",
    reason: "Panlobular emphysema (J43.1) and centrilobular emphysema (J43.2) are anatomically distinct subtypes. A patient typically presents with one predominant pattern per diagnosis.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J20",
    code2: "J42",
    type: "mutually_exclusive",
    reason: "Acute bronchitis (J20) and unspecified chronic bronchitis (J42) represent different disease phases. If a patient has chronic bronchitis with an acute exacerbation, the exacerbation should be coded appropriately — not as a new acute bronchitis.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J20",
    code2: "J41",
    type: "mutually_exclusive",
    reason: "Acute bronchitis (J20) and simple/mucopurulent chronic bronchitis (J41) — acute bronchitis in a patient with established chronic bronchitis should be coded as an exacerbation, not as separate concurrent diagnoses.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J20",
    code2: "J40",
    type: "mutually_exclusive",
    reason: "Acute bronchitis (J20) and bronchitis not specified as acute or chronic (J40) — J40 is an unspecified code that becomes redundant when the specific acute code (J20) is assigned.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J01",
    code2: "J32",
    type: "mutually_exclusive",
    reason: "Acute sinusitis (J01) and chronic sinusitis (J32) at the same anatomical site represent different disease stages. Acute-on-chronic should use the acute code with documentation, not both codes simultaneously.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J01.0",
    code2: "J32.0",
    type: "mutually_exclusive",
    reason: "Acute maxillary sinusitis (J01.0) and chronic maxillary sinusitis (J32.0) at the same site on the same claim represents a temporal coding conflict.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J01.1",
    code2: "J32.1",
    type: "mutually_exclusive",
    reason: "Acute frontal sinusitis (J01.1) and chronic frontal sinusitis (J32.1) — same-site acute and chronic codes should not coexist on one claim.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J45.0",
    code2: "J45.1",
    type: "mutually_exclusive",
    reason: "Predominantly allergic asthma (J45.0) and nonallergic asthma (J45.1) represent mutually exclusive asthma phenotypes on a single encounter.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for asthma (CDL 3)",
    category: "icd10_exclusion",
  },
  {
    code1: "J18.0",
    code2: "J18.9",
    type: "mutually_exclusive",
    reason: "Bronchopneumonia, unspecified (J18.0) and pneumonia, unspecified (J18.9) — two unspecified pneumonia codes should not coexist. Use the most specific available.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J44.0",
    code2: "J44.1",
    type: "mutually_exclusive",
    reason: "COPD with acute lower respiratory infection (J44.0) and COPD with acute exacerbation (J44.1) — only one exacerbation type should be coded per encounter.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J12.0",
    code2: "J12.1",
    type: "mutually_exclusive",
    reason: "Adenoviral pneumonia (J12.0) and RSV pneumonia (J12.1) are caused by different viruses. Co-infection is rare and requires specific documentation to code both.",
    source: "WHO ICD-10 coding conventions; SA MIT coding standards",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. GENDER-IMPOSSIBLE COMBINATIONS (~40)
  // Male-only codes (N40-N51, C60-C63, D29, D40) vs
  // Female-only codes (O00-O99, N70-N98, C51-C58, D06, D25-D28, D39)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "N40",
    code2: "O80",
    type: "mutually_exclusive",
    reason: "Prostatic hyperplasia (N40) is a male-only condition. Single spontaneous delivery (O80) is a female-only obstetric code. These codes cannot coexist on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N40",
    code2: "N83",
    type: "mutually_exclusive",
    reason: "Prostatic hyperplasia (N40, male-only) cannot coexist with noninflammatory disorders of ovary and fallopian tube (N83, female-only) on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N41",
    code2: "O00",
    type: "mutually_exclusive",
    reason: "Inflammatory diseases of prostate (N41, male-only) and ectopic pregnancy (O00, female-only) cannot appear on the same claim — gender-impossible combination.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N41",
    code2: "N70",
    type: "mutually_exclusive",
    reason: "Prostatitis (N41, male-only) and salpingitis/oophoritis (N70, female-only) are gender-exclusive conditions that cannot coexist on one patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N42",
    code2: "C53",
    type: "mutually_exclusive",
    reason: "Other disorders of prostate (N42, male-only) and malignant neoplasm of cervix uteri (C53, female-only) are anatomically impossible on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N43",
    code2: "O20",
    type: "mutually_exclusive",
    reason: "Hydrocele and spermatocele (N43, male-only) and haemorrhage in early pregnancy (O20, female-only) cannot coexist — gender-impossible coding.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N44",
    code2: "N75",
    type: "mutually_exclusive",
    reason: "Torsion of testis (N44, male-only) and diseases of Bartholin gland (N75, female-only) are anatomically impossible on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N45",
    code2: "C54",
    type: "mutually_exclusive",
    reason: "Orchitis and epididymitis (N45, male-only) and malignant neoplasm of corpus uteri (C54, female-only) are gender-impossible diagnoses on one claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N47",
    code2: "O46",
    type: "mutually_exclusive",
    reason: "Redundant prepuce, phimosis and paraphimosis (N47, male-only) and antepartum haemorrhage (O46, female-only) cannot coexist on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N48",
    code2: "N80",
    type: "mutually_exclusive",
    reason: "Other disorders of penis (N48, male-only) and endometriosis (N80, female-only) are gender-exclusive diagnoses.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N50",
    code2: "N84",
    type: "mutually_exclusive",
    reason: "Other disorders of male genital organs (N50, male-only) and polyp of female genital tract (N84, female-only) — gender-impossible combination.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "C51",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of prostate (C61, male-only) and malignant neoplasm of vulva (C51, female-only) cannot appear on the same patient's claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "C52",
    type: "mutually_exclusive",
    reason: "Prostate cancer (C61, male-only) and vaginal cancer (C52, female-only) are gender-impossible on the same claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "C53",
    type: "mutually_exclusive",
    reason: "Prostate cancer (C61, male-only) and cervical cancer (C53, female-only) — anatomically impossible on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "C54",
    type: "mutually_exclusive",
    reason: "Prostate cancer (C61, male-only) and uterine corpus cancer (C54, female-only) are gender-exclusive conditions.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "C56",
    type: "mutually_exclusive",
    reason: "Prostate cancer (C61, male-only) and ovarian cancer (C56, female-only) cannot coexist on one patient's claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "O80",
    type: "mutually_exclusive",
    reason: "Prostate cancer (C61, male-only) and single spontaneous delivery (O80, female-only) — gender-impossible combination.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C62",
    code2: "C55",
    type: "mutually_exclusive",
    reason: "Testicular cancer (C62, male-only) and malignant neoplasm of uterus, part unspecified (C55, female-only) are gender-impossible on one claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C62",
    code2: "C57",
    type: "mutually_exclusive",
    reason: "Testicular cancer (C62, male-only) and malignant neoplasm of other female genital organs (C57, female-only) — gender-exclusive diagnoses.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C60",
    code2: "C58",
    type: "mutually_exclusive",
    reason: "Penile cancer (C60, male-only) and malignant neoplasm of placenta (C58, female-only) — anatomically impossible on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C63",
    code2: "D06",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of other male genital organs (C63, male-only) and carcinoma in situ of cervix uteri (D06, female-only) — gender-impossible.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "D29",
    code2: "D25",
    type: "mutually_exclusive",
    reason: "Benign neoplasm of male genital organs (D29) and leiomyoma of uterus (D25, female-only) are gender-exclusive conditions.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "D29",
    code2: "D26",
    type: "mutually_exclusive",
    reason: "Benign neoplasm of male genital organs (D29) and other benign neoplasms of uterus (D26, female-only) — gender-impossible combination.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "D29",
    code2: "D27",
    type: "mutually_exclusive",
    reason: "Benign neoplasm of male genital organs (D29) and benign neoplasm of ovary (D27, female-only) cannot appear on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "D29",
    code2: "D28",
    type: "mutually_exclusive",
    reason: "Benign neoplasm of male genital organs (D29) and benign neoplasm of other female genital organs (D28, female-only) — gender-impossible pairing.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "D40",
    code2: "D39",
    type: "mutually_exclusive",
    reason: "Neoplasm of uncertain behaviour of male genital organs (D40) and neoplasm of uncertain behaviour of female genital organs (D39) — gender-exclusive conditions.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N40",
    code2: "C56",
    type: "mutually_exclusive",
    reason: "Prostatic hyperplasia (N40, male-only) and ovarian cancer (C56, female-only) are anatomically impossible on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N45",
    code2: "N92",
    type: "mutually_exclusive",
    reason: "Orchitis and epididymitis (N45, male-only) and excessive, frequent or irregular menstruation (N92, female-only) — gender-impossible combination.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N46",
    code2: "N97",
    type: "mutually_exclusive",
    reason: "Male infertility (N46) and female infertility (N97) cannot appear on the same patient's claim — these are gender-specific diagnoses.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C60",
    code2: "D25",
    type: "mutually_exclusive",
    reason: "Penile cancer (C60, male-only) and uterine leiomyoma (D25, female-only) — gender-impossible combination.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N51",
    code2: "N76",
    type: "mutually_exclusive",
    reason: "Disorders of male genital organs in diseases classified elsewhere (N51, male-only) and other inflammation of vagina and vulva (N76, female-only) — gender-exclusive.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C62",
    code2: "O21",
    type: "mutually_exclusive",
    reason: "Testicular cancer (C62, male-only) and excessive vomiting in pregnancy (O21, female-only) — gender-impossible on the same patient.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N40",
    code2: "D06",
    type: "mutually_exclusive",
    reason: "Prostatic hyperplasia (N40, male-only) and carcinoma in situ of cervix uteri (D06, female-only) cannot coexist — gender-impossible.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C61",
    code2: "D25",
    type: "mutually_exclusive",
    reason: "Prostate cancer (C61, male-only) and uterine leiomyoma (D25, female-only) — gender-impossible pairing on the same claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N47",
    code2: "N85",
    type: "mutually_exclusive",
    reason: "Phimosis/paraphimosis (N47, male-only) and other noninflammatory disorders of uterus (N85, female-only) — gender-exclusive diagnoses.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C63",
    code2: "O99",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of other male genital organs (C63) and other maternal diseases classifiable elsewhere but complicating pregnancy (O99) — gender-impossible.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "D40",
    code2: "N87",
    type: "mutually_exclusive",
    reason: "Neoplasm of uncertain behaviour of male genital organs (D40, male-only) and dysplasia of cervix uteri (N87, female-only) — gender-impossible.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N48",
    code2: "O60",
    type: "mutually_exclusive",
    reason: "Disorders of penis (N48, male-only) and preterm labour (O60, female-only) are gender-impossible on the same patient's claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "C60",
    code2: "N91",
    type: "mutually_exclusive",
    reason: "Penile cancer (C60, male-only) and absent, scanty or rare menstruation (N91, female-only) — gender-impossible on one claim.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },
  {
    code1: "N49",
    code2: "C56",
    type: "mutually_exclusive",
    reason: "Inflammatory disorders of male genital organs (N49, male-only) and ovarian cancer (C56, female-only) — gender-exclusive conditions that cannot coexist.",
    source: "WHO ICD-10 gender-specific coding rules; SA MIT validation",
    category: "gender_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. ACUTE VS CHRONIC EXCLUSIONS (~30)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "B16",
    code2: "B18.1",
    type: "mutually_exclusive",
    reason: "Acute hepatitis B (B16) and chronic viral hepatitis B (B18.1) represent different disease phases. A patient has either an acute infection or has progressed to chronic — coding both simultaneously is a staging conflict.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for hepatitis (CDL 13)",
    category: "icd10_exclusion",
  },
  {
    code1: "K25.0",
    code2: "K25.4",
    type: "mutually_exclusive",
    reason: "Acute gastric ulcer with haemorrhage (K25.0) and chronic gastric ulcer with haemorrhage (K25.4) cannot coexist — the ulcer is either acute or chronic at the time of the encounter.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K25.1",
    code2: "K25.5",
    type: "mutually_exclusive",
    reason: "Acute gastric ulcer with perforation (K25.1) and chronic gastric ulcer with perforation (K25.5) are temporally mutually exclusive — the ulcer cannot be both acute and chronic simultaneously.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "N17",
    code2: "N18",
    type: "mutually_exclusive",
    reason: "Acute renal failure (N17) and chronic renal failure (N18) represent different disease stages. While acute-on-chronic kidney disease exists, it should be coded specifically — not as separate acute and chronic codes.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for renal disease (CDL 8)",
    category: "icd10_exclusion",
  },
  {
    code1: "I20",
    code2: "I25",
    type: "mutually_exclusive",
    reason: "Angina pectoris (I20) as an acute presentation and chronic ischaemic heart disease (I25) — if the patient is presenting with acute angina, this is the active diagnosis. Chronic IHD is the underlying condition. Dual coding on the same acute encounter is flagged for review.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for coronary artery disease (CDL 5)",
    category: "icd10_exclusion",
  },
  {
    code1: "K50",
    code2: "K51",
    type: "mutually_exclusive",
    reason: "Crohn disease (K50) and ulcerative colitis (K51) are distinct inflammatory bowel diseases with different pathological features. While rare indeterminate colitis exists, coding both is a diagnostic error in most cases.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for Crohn disease (CDL 6)",
    category: "icd10_exclusion",
  },
  {
    code1: "H10.0",
    code2: "H10.4",
    type: "mutually_exclusive",
    reason: "Acute conjunctivitis (H10.0) and chronic conjunctivitis (H10.4) at the same encounter — the condition is either in acute phase or chronic phase, not both simultaneously.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "H65.0",
    code2: "H65.2",
    type: "mutually_exclusive",
    reason: "Acute serous otitis media (H65.0) and chronic serous otitis media (H65.2) represent different disease stages. An acute-on-chronic situation should be coded with the acute code.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K81.0",
    code2: "K81.1",
    type: "mutually_exclusive",
    reason: "Acute cholecystitis (K81.0) and chronic cholecystitis (K81.1) — if the patient presents with acute cholecystitis, that is the active diagnosis. Acute-on-chronic should use the acute code.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I30.0",
    code2: "I31.0",
    type: "mutually_exclusive",
    reason: "Acute nonspecific idiopathic pericarditis (I30.0) and chronic adhesive pericarditis (I31.0) — temporal conflict. The pericarditis is either in an acute inflammatory phase or has progressed to chronic adhesive disease.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J20",
    code2: "J42",
    type: "mutually_exclusive",
    reason: "Acute bronchitis (J20) and unspecified chronic bronchitis (J42) — coding both implies simultaneous acute and chronic bronchitis, which is a temporal conflict. Use the acute code for the current episode.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "M65.0",
    code2: "M65.8",
    type: "mutually_exclusive",
    reason: "Abscess of tendon sheath (M65.0, acute) and other synovitis and tenosynovitis (M65.8, often chronic) — if the acute abscess is the presenting condition, it supersedes the chronic code for the same site.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K85",
    code2: "K86.1",
    type: "mutually_exclusive",
    reason: "Acute pancreatitis (K85) and other chronic pancreatitis (K86.1) are temporally exclusive. During an acute episode, K85 is coded. Chronic pancreatitis as a background condition should not be dual-coded on the same acute encounter.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "N10",
    code2: "N11",
    type: "mutually_exclusive",
    reason: "Acute tubulo-interstitial nephritis / pyelonephritis (N10) and chronic tubulo-interstitial nephritis (N11) — the infection is either in acute phase or chronic phase. Acute-on-chronic should use the acute code.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I01",
    code2: "I09",
    type: "mutually_exclusive",
    reason: "Rheumatic fever with heart involvement (I01, acute) and rheumatic heart disease (I09, chronic sequelae) — the patient is either in an active rheumatic fever episode or has chronic rheumatic heart disease, not both simultaneously.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "H04.0",
    code2: "H04.1",
    type: "mutually_exclusive",
    reason: "Dacryoadenitis (H04.0, acute) and chronic disorders of lacrimal gland (H04.1) — temporal staging conflict. Code the active presenting condition.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "N30.0",
    code2: "N30.1",
    type: "mutually_exclusive",
    reason: "Acute cystitis (N30.0) and interstitial cystitis / chronic cystitis (N30.1) are temporally exclusive. The current episode is coded as either acute or chronic.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "L51",
    code2: "L40",
    type: "mutually_exclusive",
    reason: "Erythema multiforme (L51, acute hypersensitivity reaction) and psoriasis (L40, chronic skin disease) are distinct dermatological diagnoses with different pathophysiology — not different phases of the same condition, but often miscoded as dual diagnoses.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "M54.4",
    code2: "M54.5",
    type: "mutually_exclusive",
    reason: "Lumbago with sciatica (M54.4) and low back pain (M54.5, lumbago without sciatica) are mutually exclusive — the patient either has radiculopathy (sciatica) or does not. Code the most specific presentation.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K25.0",
    code2: "K25.7",
    type: "mutually_exclusive",
    reason: "Acute gastric ulcer with haemorrhage (K25.0) and chronic gastric ulcer without haemorrhage or perforation (K25.7) — temporal conflict between acute and chronic ulcer coding.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K26.0",
    code2: "K26.4",
    type: "mutually_exclusive",
    reason: "Acute duodenal ulcer with haemorrhage (K26.0) and chronic duodenal ulcer with haemorrhage (K26.4) — the ulcer is either acute or chronic, not both.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "B17.1",
    code2: "B18.2",
    type: "mutually_exclusive",
    reason: "Acute hepatitis C (B17.1) and chronic viral hepatitis C (B18.2) are temporally exclusive. The infection is either in its acute phase or has become chronic.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "H66.0",
    code2: "H66.1",
    type: "mutually_exclusive",
    reason: "Acute suppurative otitis media (H66.0) and chronic tubotympanic suppurative otitis media (H66.1) — temporal staging conflict for the same condition.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J03",
    code2: "J35.0",
    type: "mutually_exclusive",
    reason: "Acute tonsillitis (J03) and chronic tonsillitis (J35.0) represent different disease stages. An acute exacerbation in chronic tonsillitis should be coded as acute tonsillitis.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K35",
    code2: "K36",
    type: "mutually_exclusive",
    reason: "Acute appendicitis (K35) and other appendicitis (K36, including chronic) — if appendicitis is acute, K35 is definitive. K36 should not be coded alongside K35.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "I20.0",
    code2: "I25.1",
    type: "mutually_exclusive",
    reason: "Unstable angina (I20.0, acute presentation) and atherosclerotic heart disease (I25.1, chronic condition) — the acute event takes precedence for encounter coding. Dual coding inflates diagnostic complexity.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for coronary artery disease",
    category: "icd10_exclusion",
  },
  {
    code1: "H20.0",
    code2: "H20.1",
    type: "mutually_exclusive",
    reason: "Acute and subacute iridocyclitis (H20.0) and chronic iridocyclitis (H20.1) are temporally mutually exclusive — the inflammation is in acute or chronic phase, not both.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "K75.0",
    code2: "K73",
    type: "mutually_exclusive",
    reason: "Liver abscess (K75.0, acute hepatic inflammation) and chronic hepatitis, not elsewhere classified (K73) — the acute abscess is the presenting condition and should not be dual-coded with chronic hepatitis of different aetiology.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "J00",
    code2: "J31.0",
    type: "mutually_exclusive",
    reason: "Acute nasopharyngitis / common cold (J00) and chronic rhinitis (J31.0) — the acute viral infection should be coded separately; chronic rhinitis is a different condition that should not appear alongside the acute presentation.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "N00",
    code2: "N03",
    type: "mutually_exclusive",
    reason: "Acute nephritic syndrome (N00) and chronic nephritic syndrome (N03) represent different disease phases of glomerulonephritis. Code the current presentation only.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. SPECIFIC VS UNSPECIFIED (~40)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "E05.0",
    code2: "E05.9",
    type: "mutually_exclusive",
    reason: "Thyrotoxicosis with diffuse goitre / Graves disease (E05.0) is a specific diagnosis. Thyrotoxicosis, unspecified (E05.9) is redundant when the specific subtype is known.",
    source: "WHO ICD-10 coding conventions; BHF coding guidelines",
    category: "specificity_conflict",
  },
  {
    code1: "I21.0",
    code2: "I21.9",
    type: "mutually_exclusive",
    reason: "Acute transmural MI of anterior wall (I21.0) is specific. Acute MI, unspecified (I21.9) must not be coded alongside it — the wall location has been identified.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for AMI",
    category: "specificity_conflict",
  },
  {
    code1: "I21.1",
    code2: "I21.9",
    type: "mutually_exclusive",
    reason: "Acute transmural MI of inferior wall (I21.1) is specific. Acute MI, unspecified (I21.9) is superseded by the specific wall location code.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for AMI",
    category: "specificity_conflict",
  },
  {
    code1: "K35.0",
    code2: "K35.9",
    type: "mutually_exclusive",
    reason: "Acute appendicitis with generalised peritonitis (K35.0) is specific. Acute appendicitis, unspecified (K35.9) should not appear when the complication status is known.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "J06.0",
    code2: "J06.9",
    type: "mutually_exclusive",
    reason: "Acute laryngopharyngitis (J06.0) is a specific upper respiratory infection. Acute URTI, unspecified (J06.9) is redundant when the specific site is identified.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "K80.0",
    code2: "K80.2",
    type: "mutually_exclusive",
    reason: "Calculus of gallbladder with acute cholecystitis (K80.0) and calculus of gallbladder without cholecystitis (K80.2) — the stone either has associated inflammation or not. These are mutually exclusive states.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "M54.3",
    code2: "M54.5",
    type: "mutually_exclusive",
    reason: "Sciatica (M54.3) and low back pain / lumbago (M54.5) — sciatica is a specific radicular syndrome. If sciatica is present, the generic lumbago code is subsumed.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "G43.0",
    code2: "G43.9",
    type: "mutually_exclusive",
    reason: "Migraine without aura (G43.0) is a specific migraine type. Migraine, unspecified (G43.9) is redundant when the aura status is documented.",
    source: "WHO ICD-10 coding conventions; BHF coding guidelines",
    category: "specificity_conflict",
  },
  {
    code1: "G43.1",
    code2: "G43.9",
    type: "mutually_exclusive",
    reason: "Migraine with aura (G43.1) is specific. Migraine, unspecified (G43.9) should not be coded alongside the specific subtype.",
    source: "WHO ICD-10 coding conventions; BHF coding guidelines",
    category: "specificity_conflict",
  },
  {
    code1: "N20.0",
    code2: "N20.9",
    type: "mutually_exclusive",
    reason: "Calculus of kidney (N20.0) is specific. Urinary calculus, unspecified (N20.9) is redundant when the stone location is documented.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "L50.0",
    code2: "L50.9",
    type: "mutually_exclusive",
    reason: "Allergic urticaria (L50.0) is a specific subtype. Urticaria, unspecified (L50.9) is redundant when the allergic aetiology is established.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "J45.0",
    code2: "J45.9",
    type: "mutually_exclusive",
    reason: "Predominantly allergic asthma (J45.0) is specific. Asthma, unspecified (J45.9) should not appear when the asthma phenotype is documented.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for asthma (CDL 3)",
    category: "specificity_conflict",
  },
  {
    code1: "K29.0",
    code2: "K29.9",
    type: "mutually_exclusive",
    reason: "Acute haemorrhagic gastritis (K29.0) is specific. Gastroduodenitis, unspecified (K29.9) is superseded by the specific diagnosis.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "K29.1",
    code2: "K29.9",
    type: "mutually_exclusive",
    reason: "Other acute gastritis (K29.1) is specific. Gastroduodenitis, unspecified (K29.9) should not accompany the specific subtype code.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "E11.0",
    code2: "E11.9",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes with coma (E11.0) is a specific complication. Type 2 diabetes without complications (E11.9) contradicts E11.0 which documents a complication.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "specificity_conflict",
  },
  {
    code1: "I50.0",
    code2: "I50.9",
    type: "mutually_exclusive",
    reason: "Congestive heart failure (I50.0) is specific. Heart failure, unspecified (I50.9) is redundant when the type (congestive) is known.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for cardiac failure (CDL 1)",
    category: "specificity_conflict",
  },
  {
    code1: "I50.1",
    code2: "I50.9",
    type: "mutually_exclusive",
    reason: "Left ventricular failure (I50.1) is specific. Heart failure, unspecified (I50.9) should not accompany a specific heart failure subtype.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for cardiac failure",
    category: "specificity_conflict",
  },
  {
    code1: "J18.0",
    code2: "J18.9",
    type: "mutually_exclusive",
    reason: "Bronchopneumonia, unspecified (J18.0) is more specific than pneumonia, unspecified (J18.9). The more specific code takes precedence.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "K70.0",
    code2: "K70.9",
    type: "mutually_exclusive",
    reason: "Alcoholic fatty liver (K70.0) is a specific stage. Alcoholic liver disease, unspecified (K70.9) is redundant when the specific stage is documented.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "K70.1",
    code2: "K70.9",
    type: "mutually_exclusive",
    reason: "Alcoholic hepatitis (K70.1) is specific. Alcoholic liver disease, unspecified (K70.9) should be replaced by the specific stage code.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "N39.0",
    code2: "N39.9",
    type: "mutually_exclusive",
    reason: "Urinary tract infection, site not specified (N39.0) is more informative than disorder of urinary system, unspecified (N39.9). Do not code both.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "E11.2",
    code2: "E11.9",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes with renal complications (E11.2) documents a complication. Type 2 diabetes without complications (E11.9) directly contradicts this.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "specificity_conflict",
  },
  {
    code1: "E11.3",
    code2: "E11.9",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes with ophthalmic complications (E11.3) indicates diabetic eye disease. Type 2 diabetes without complications (E11.9) is contradictory.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "specificity_conflict",
  },
  {
    code1: "E11.4",
    code2: "E11.9",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes with neurological complications (E11.4) documents neuropathy. Type 2 diabetes without complications (E11.9) cannot coexist.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "specificity_conflict",
  },
  {
    code1: "E10.2",
    code2: "E10.9",
    type: "mutually_exclusive",
    reason: "Type 1 diabetes with renal complications (E10.2) and Type 1 diabetes without complications (E10.9) are contradictory — complications are either present or absent.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for diabetes",
    category: "specificity_conflict",
  },
  {
    code1: "G40.0",
    code2: "G40.9",
    type: "mutually_exclusive",
    reason: "Localisation-related epilepsy with simple partial seizures (G40.0) is specific. Epilepsy, unspecified (G40.9) should not be coded when the seizure type is known.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for epilepsy (CDL 9)",
    category: "specificity_conflict",
  },
  {
    code1: "G40.1",
    code2: "G40.9",
    type: "mutually_exclusive",
    reason: "Localisation-related epilepsy with complex partial seizures (G40.1) is specific. Epilepsy, unspecified (G40.9) is redundant when the subtype is classified.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for epilepsy",
    category: "specificity_conflict",
  },
  {
    code1: "J45.1",
    code2: "J45.9",
    type: "mutually_exclusive",
    reason: "Nonallergic asthma (J45.1) is a specific phenotype. Asthma, unspecified (J45.9) is redundant when the phenotype is known.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for asthma",
    category: "specificity_conflict",
  },
  {
    code1: "K80.1",
    code2: "K80.2",
    type: "mutually_exclusive",
    reason: "Calculus of gallbladder with other cholecystitis (K80.1) and calculus without cholecystitis (K80.2) — the gallstone either has associated inflammation or not.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "N20.1",
    code2: "N20.9",
    type: "mutually_exclusive",
    reason: "Calculus of ureter (N20.1) is specific. Urinary calculus, unspecified (N20.9) is redundant when the stone location is identified.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 7. CANCER STAGING CONFLICTS (~25)
  // Malignant (C) vs In-situ (D) for same anatomical site
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "C50",
    code2: "D05",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of breast (C50) and carcinoma in situ of breast (D05) cannot coexist for the same breast. Cancer is either invasive (C50) or pre-invasive/in situ (D05) — coding both implies contradictory staging.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C53",
    code2: "D06",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of cervix uteri (C53) and carcinoma in situ of cervix uteri (D06) represent different cancer stages. If invasive cancer is confirmed, the in situ code is no longer applicable.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C18",
    code2: "D01.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of colon (C18) and carcinoma in situ of colon (D01.0) — invasive and in situ colon cancer at the same site are staging-incompatible on one claim.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C20",
    code2: "D01.1",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of rectum (C20) and carcinoma in situ of rectum (D01.1) — the rectal neoplasm is either invasive or in situ, not both.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C43",
    code2: "D03",
    type: "mutually_exclusive",
    reason: "Malignant melanoma of skin (C43) and melanoma in situ (D03) at the same site are staging-incompatible. If the melanoma has invaded, D03 no longer applies.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C67",
    code2: "D09.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of bladder (C67) and carcinoma in situ of bladder (D09.0) — bladder cancer is staged as either invasive or in situ, not both simultaneously.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C15",
    code2: "D00.1",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of oesophagus (C15) and carcinoma in situ of oesophagus (D00.1) — staging conflict between invasive and pre-invasive disease.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C16",
    code2: "D00.2",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of stomach (C16) and carcinoma in situ of stomach (D00.2) at the same site — incompatible staging codes.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C34",
    code2: "D02.2",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of bronchus/lung (C34) and carcinoma in situ of bronchus/lung (D02.2) — lung cancer at the same site cannot be both invasive and in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C61",
    code2: "D07.5",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of prostate (C61) and carcinoma in situ of prostate (D07.5) — staging conflict. The prostate cancer is either invasive or in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C54",
    code2: "D07.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of corpus uteri / endometrium (C54) and carcinoma in situ of endometrium (D07.0) — incompatible staging for the same anatomical site.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C51",
    code2: "D07.1",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of vulva (C51) and carcinoma in situ of vulva (D07.1) — staging conflict between invasive and pre-invasive vulval cancer.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C52",
    code2: "D07.2",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of vagina (C52) and carcinoma in situ of vagina (D07.2) — the vaginal neoplasm is either invasive or in situ, not both.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C60",
    code2: "D07.4",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of penis (C60) and carcinoma in situ of penis (D07.4) — staging conflict at the same anatomical site.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C21",
    code2: "D01.3",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of anus (C21) and carcinoma in situ of anus (D01.3) — invasive and in situ anal cancer are staging-incompatible on one claim.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C22",
    code2: "D01.5",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of liver (C22) and carcinoma in situ of liver (D01.5) — the hepatic neoplasm is either invasive or pre-invasive.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C25",
    code2: "D01.7",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of pancreas (C25) and carcinoma in situ of other digestive organs including pancreas (D01.7) — staging conflict.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C64",
    code2: "D09.1",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of kidney (C64) and carcinoma in situ of other urinary organs including kidney (D09.1) — renal cell carcinoma cannot be both invasive and in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C73",
    code2: "D09.3",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of thyroid gland (C73) and carcinoma in situ of thyroid (D09.3) — staging conflict. Thyroid cancer is either invasive or in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C32",
    code2: "D02.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of larynx (C32) and carcinoma in situ of larynx (D02.0) — laryngeal cancer staging conflict between invasive and in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C33",
    code2: "D02.1",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of trachea (C33) and carcinoma in situ of trachea (D02.1) — tracheal cancer cannot be coded as both invasive and pre-invasive.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C00",
    code2: "D00.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of lip (C00) and carcinoma in situ of lip, oral cavity and pharynx (D00.0) — staging conflict for lip neoplasm between invasive and in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C04",
    code2: "D00.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of floor of mouth (C04) and carcinoma in situ of oral cavity (D00.0) — invasive and in situ oral cancer at the same site are incompatible.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C06",
    code2: "D00.0",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of other parts of mouth (C06) and carcinoma in situ of oral cavity (D00.0) — staging conflict for oral cavity neoplasm.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "C44",
    code2: "D04",
    type: "mutually_exclusive",
    reason: "Other malignant neoplasms of skin (C44, non-melanoma) and carcinoma in situ of skin (D04) at the same site — the skin cancer is either invasive or in situ.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 8. HIV STAGING CONFLICTS (~10)
  // B20-B24 = symptomatic HIV; Z21 = asymptomatic HIV status
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "B20",
    code2: "Z21",
    type: "mutually_exclusive",
    reason: "HIV disease resulting in infectious and parasitic diseases (B20) indicates symptomatic HIV/AIDS. Asymptomatic HIV infection status (Z21) is contradictory — the patient is symptomatic.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV (CDL 15)",
    category: "icd10_exclusion",
  },
  {
    code1: "B21",
    code2: "Z21",
    type: "mutually_exclusive",
    reason: "HIV disease resulting in malignant neoplasms (B21) documents symptomatic AIDS. Asymptomatic HIV status (Z21) is incompatible with active AIDS-defining malignancy.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B22",
    code2: "Z21",
    type: "mutually_exclusive",
    reason: "HIV disease resulting in other specified diseases (B22) confirms symptomatic HIV/AIDS. Asymptomatic status (Z21) cannot coexist with documented HIV-related disease.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B23",
    code2: "Z21",
    type: "mutually_exclusive",
    reason: "HIV disease resulting in other conditions (B23) including acute seroconversion, lymphadenopathy, and haematological abnormalities is symptomatic. Z21 (asymptomatic) is contradictory.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B24",
    code2: "Z21",
    type: "mutually_exclusive",
    reason: "Unspecified HIV disease (B24) still implies symptomatic/clinical HIV. Asymptomatic HIV status (Z21) should be used only when no clinical manifestations are present.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B20",
    code2: "B24",
    type: "mutually_exclusive",
    reason: "HIV resulting in infectious diseases (B20) is a specific symptomatic code. Unspecified HIV disease (B24) is redundant when the specific manifestation category is identified.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B21",
    code2: "B24",
    type: "mutually_exclusive",
    reason: "HIV resulting in malignant neoplasms (B21) is specific. Unspecified HIV disease (B24) should not be coded alongside the specific manifestation code.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B22",
    code2: "B24",
    type: "mutually_exclusive",
    reason: "HIV resulting in other specified diseases (B22) is specific. Unspecified HIV disease (B24) is superseded and should not accompany B22.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B20",
    code2: "B23.0",
    type: "mutually_exclusive",
    reason: "HIV resulting in infectious diseases (B20) represents established AIDS-defining illness. Acute HIV infection syndrome (B23.0) represents the initial seroconversion — these are different disease stages.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },
  {
    code1: "B23.0",
    code2: "B24",
    type: "mutually_exclusive",
    reason: "Acute HIV infection syndrome (B23.0) is a specific early-stage presentation. Unspecified HIV disease (B24) should not be coded alongside this specific code.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for HIV",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 9. MENTAL HEALTH TYPE EXCLUSIONS (~25)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "F20",
    code2: "F25",
    type: "mutually_exclusive",
    reason: "Schizophrenia (F20) and schizoaffective disorders (F25) are mutually exclusive diagnoses. Schizoaffective disorder is a distinct entity with concurrent mood and psychotic features — it is not schizophrenia plus a mood disorder.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F30",
    code2: "F32",
    type: "mutually_exclusive",
    reason: "Manic episode (F30) and depressive episode (F32) are opposing mood states. A patient cannot be experiencing a manic and depressive episode simultaneously (mixed states are coded under F31, bipolar disorder).",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F31",
    code2: "F33",
    type: "mutually_exclusive",
    reason: "Bipolar affective disorder (F31) and recurrent depressive disorder (F33) are mutually exclusive. If a patient has ever had a manic/hypomanic episode, F31 is used — not F33. Recurrent depression without mania history is F33.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F30",
    code2: "F31",
    type: "mutually_exclusive",
    reason: "Single manic episode (F30) and bipolar affective disorder (F31) — if the patient has a history of bipolar episodes, F31 is used. F30 is only for a first manic episode without prior mood episodes.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F32",
    code2: "F33",
    type: "mutually_exclusive",
    reason: "Single depressive episode (F32) and recurrent depressive disorder (F33) — if the patient has had previous depressive episodes, F33 applies. F32 is for first-episode depression only.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F00",
    code2: "F01",
    type: "mutually_exclusive",
    reason: "Dementia in Alzheimer disease (F00) and vascular dementia (F01) represent different aetiological subtypes. While mixed dementia exists, it requires specific documentation — dual coding without evidence is flagged.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F00",
    code2: "F02",
    type: "mutually_exclusive",
    reason: "Dementia in Alzheimer disease (F00) and dementia in other diseases classified elsewhere (F02) have different underlying aetiologies and are mutually exclusive unless mixed dementia is specifically documented.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F00",
    code2: "F03",
    type: "mutually_exclusive",
    reason: "Dementia in Alzheimer disease (F00) is a specific diagnosis. Unspecified dementia (F03) is redundant and contradictory when the Alzheimer aetiology is established.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F01",
    code2: "F03",
    type: "mutually_exclusive",
    reason: "Vascular dementia (F01) is a specific diagnosis. Unspecified dementia (F03) should not be coded alongside an aetiologically defined dementia subtype.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F01",
    code2: "F02",
    type: "mutually_exclusive",
    reason: "Vascular dementia (F01) and dementia in other diseases (F02) have different underlying aetiologies. Only the confirmed primary cause should be coded unless mixed dementia is documented.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F02",
    code2: "F03",
    type: "mutually_exclusive",
    reason: "Dementia in other diseases classified elsewhere (F02) is specific. Unspecified dementia (F03) is redundant when the underlying cause is identified.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F40",
    code2: "F41",
    type: "mutually_exclusive",
    reason: "Phobic anxiety disorders (F40) and other anxiety disorders (F41) — while comorbidity is possible, dual coding is flagged as these overlap diagnostically. Generalised anxiety (F41.1) with specific phobia (F40.2) requires separate documentation.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F42",
    code2: "F60.5",
    type: "mutually_exclusive",
    reason: "Obsessive-compulsive disorder (F42) and anankastic personality disorder (F60.5) are diagnostically distinct. OCD involves ego-dystonic intrusive thoughts; anankastic PD involves ego-syntonic perfectionism. Dual coding suggests diagnostic confusion.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F50.0",
    code2: "F50.2",
    type: "mutually_exclusive",
    reason: "Anorexia nervosa (F50.0) and bulimia nervosa (F50.2) are mutually exclusive eating disorder diagnoses. A patient meets criteria for one or the other — the binge-purge subtype of anorexia is still coded under F50.0.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F84.0",
    code2: "F84.5",
    type: "mutually_exclusive",
    reason: "Childhood autism (F84.0) and Asperger syndrome (F84.5) are mutually exclusive pervasive developmental disorder diagnoses in ICD-10. Asperger syndrome is distinguished by absence of language delay.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F20",
    code2: "F22",
    type: "mutually_exclusive",
    reason: "Schizophrenia (F20) and persistent delusional disorders (F22) are distinct diagnoses. F22 lacks the full schizophrenic symptom complex — the two should not be coded together.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F20",
    code2: "F23",
    type: "mutually_exclusive",
    reason: "Schizophrenia (F20) and acute and transient psychotic disorders (F23) — F23 is used for brief psychotic episodes not meeting schizophrenia criteria. If schizophrenia is diagnosed, F23 no longer applies.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F10.0",
    code2: "F10.2",
    type: "mutually_exclusive",
    reason: "Acute alcohol intoxication (F10.0) and alcohol dependence syndrome (F10.2) — while a dependent patient can be intoxicated, coding both on the same encounter may indicate coding confusion. The dependence code (F10.2) captures the chronic condition.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F11.0",
    code2: "F11.2",
    type: "mutually_exclusive",
    reason: "Acute opioid intoxication (F11.0) and opioid dependence (F11.2) on the same encounter — if the patient is dependent, the acute intoxication is within the context of dependence. Code the most clinically significant condition.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F31",
    code2: "F30",
    type: "mutually_exclusive",
    reason: "Bipolar affective disorder (F31) encompasses manic episodes within its course. A separate manic episode code (F30) should not be used once bipolar disorder is diagnosed.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F32.0",
    code2: "F32.3",
    type: "mutually_exclusive",
    reason: "Mild depressive episode (F32.0) and severe depressive episode with psychotic symptoms (F32.3) — only one severity level should be coded per episode. These are mutually exclusive severity grades.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F32.1",
    code2: "F32.3",
    type: "mutually_exclusive",
    reason: "Moderate depressive episode (F32.1) and severe depressive episode with psychotic symptoms (F32.3) are different severity grades of the same condition — only one applies per episode.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F20.0",
    code2: "F20.5",
    type: "mutually_exclusive",
    reason: "Paranoid schizophrenia (F20.0) and residual schizophrenia (F20.5) are different subtypes/phases. A patient is either in active paranoid phase or in residual phase — not both simultaneously.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F41.0",
    code2: "F41.1",
    type: "mutually_exclusive",
    reason: "Panic disorder (F41.0) and generalised anxiety disorder (F41.1) — while comorbidity occurs, ICD-10 convention is to code the predominant disorder per encounter. Dual coding is flagged for clinical review.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "F43.0",
    code2: "F43.1",
    type: "mutually_exclusive",
    reason: "Acute stress reaction (F43.0) and post-traumatic stress disorder (F43.1) represent different temporal responses to trauma — acute (hours to days) vs chronic (persisting beyond one month). They should not be coded simultaneously.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 10. INJURY LATERALITY / SEVERITY CONFLICTS (~15)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "S72.0",
    code2: "S72.1",
    type: "mutually_exclusive",
    reason: "Fracture of neck of femur (S72.0) and pertrochanteric fracture (S72.1) on the same side — these are different anatomical locations of proximal femur fracture. A single fracture event produces one pattern, not both.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S72.0",
    code2: "S72.2",
    type: "mutually_exclusive",
    reason: "Fracture of neck of femur (S72.0) and subtrochanteric fracture (S72.2) on the same side — these are distinct proximal femur fracture patterns that rarely coexist from a single injury.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S42.0",
    code2: "S42.1",
    type: "mutually_exclusive",
    reason: "Fracture of clavicle (S42.0) and fracture of scapula (S42.1) from a single injury event — while both can occur in high-energy trauma, dual coding requires documentation of multiple distinct fractures.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S42.2",
    code2: "S42.3",
    type: "mutually_exclusive",
    reason: "Fracture of upper end of humerus (S42.2) and fracture of shaft of humerus (S42.3) — different anatomical zones of the same bone. A single fracture has one location; coding both implies two separate fractures requiring documentation.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S52.0",
    code2: "S52.1",
    type: "mutually_exclusive",
    reason: "Fracture of upper end of ulna (S52.0) and fracture of upper end of radius (S52.1) — while both forearm bones can fracture, coding both requires documentation of a complex injury pattern (e.g. Monteggia or Essex-Lopresti).",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S82.0",
    code2: "S82.1",
    type: "mutually_exclusive",
    reason: "Fracture of patella (S82.0) and fracture of upper end of tibia (S82.1) — different anatomical structures. Both can occur but requires specific documentation of multiple fractures.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S06.0",
    code2: "S06.3",
    type: "mutually_exclusive",
    reason: "Concussion (S06.0) and focal brain injury (S06.3) — concussion is a diffuse mild TBI, while focal injury implies localised damage. Coding both suggests confusion between mild diffuse and severe focal injury classifications.",
    source: "WHO ICD-10 coding conventions; SA trauma coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S06.0",
    code2: "S06.4",
    type: "mutually_exclusive",
    reason: "Concussion (S06.0) and epidural haemorrhage (S06.4) — concussion implies mild TBI without structural injury, while epidural haemorrhage is a severe structural injury. These represent different severity levels.",
    source: "WHO ICD-10 coding conventions; SA trauma coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S06.0",
    code2: "S06.5",
    type: "mutually_exclusive",
    reason: "Concussion (S06.0) and traumatic subdural haemorrhage (S06.5) — concussion is mild TBI without intracranial bleeding. Subdural haemorrhage indicates structural damage incompatible with a simple concussion diagnosis.",
    source: "WHO ICD-10 coding conventions; SA trauma coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "T20",
    code2: "T31",
    type: "mutually_exclusive",
    reason: "Burns of head and neck (T20, local burn site) and burns classified according to extent of body surface involved (T31) — T31 is a supplementary code for extent, not a standalone diagnosis. Using T20 with T31 may be correct for large burns, but T31 alone without a site code is flagged.",
    source: "WHO ICD-10 coding conventions; SA burns unit coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S62.0",
    code2: "S62.3",
    type: "mutually_exclusive",
    reason: "Fracture of navicular bone of hand (S62.0) and fracture of other metacarpal bone (S62.3) — different hand bones. While both can fracture in a crush injury, dual coding requires documentation of multiple distinct fractures.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S72.3",
    code2: "S72.4",
    type: "mutually_exclusive",
    reason: "Fracture of shaft of femur (S72.3) and fracture of lower end of femur (S72.4) — different zones of the same bone. A single fracture has one primary location code.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S82.5",
    code2: "S82.6",
    type: "mutually_exclusive",
    reason: "Fracture of medial malleolus (S82.5) and fracture of lateral malleolus (S82.6) on the same side — while bimalleolar fractures occur, they should be coded as a single complex fracture pattern (S82.8) rather than two separate codes.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S32.0",
    code2: "S32.1",
    type: "mutually_exclusive",
    reason: "Fracture of lumbar vertebra (S32.0) and fracture of sacrum (S32.1) — different anatomical structures. While both can occur in high-energy trauma, dual coding requires documented multiple fractures.",
    source: "WHO ICD-10 coding conventions; SA orthopaedic coding standards",
    category: "icd10_exclusion",
  },
  {
    code1: "S22.0",
    code2: "S22.1",
    type: "mutually_exclusive",
    reason: "Fracture of thoracic vertebra (S22.0) and fracture of sternum (S22.1) — different thoracic structures. While both can occur in high-energy deceleration, each requires separate documentation.",
    source: "WHO ICD-10 coding conventions; SA trauma coding standards",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 11. PREGNANCY EXCLUSIONS (~15)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "O00",
    code2: "O30",
    type: "mutually_exclusive",
    reason: "Ectopic pregnancy (O00) and multiple gestation (O30) cannot coexist as primary diagnoses. An ectopic pregnancy terminates the pregnancy — multiple gestation implies an ongoing intrauterine pregnancy.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O03",
    code2: "O60",
    type: "mutually_exclusive",
    reason: "Spontaneous abortion / miscarriage (O03) and preterm labour (O60) are mutually exclusive outcomes. A miscarriage ends the pregnancy before viability; preterm labour occurs in a viable pregnancy.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O00",
    code2: "O80",
    type: "mutually_exclusive",
    reason: "Ectopic pregnancy (O00) and single spontaneous delivery (O80) are incompatible — an ectopic pregnancy cannot result in a normal vaginal delivery.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O03",
    code2: "O80",
    type: "mutually_exclusive",
    reason: "Spontaneous abortion (O03) and single spontaneous delivery (O80) are mutually exclusive — the pregnancy either ends in miscarriage or in delivery, not both.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O24.0",
    code2: "E10",
    type: "mutually_exclusive",
    reason: "Pre-existing Type 1 diabetes in pregnancy (O24.0) supersedes the standard Type 1 diabetes code (E10) during pregnancy. SA obstetric coding convention requires the O-chapter code for pregnancy-related management.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O24.1",
    code2: "E11",
    type: "mutually_exclusive",
    reason: "Pre-existing Type 2 diabetes in pregnancy (O24.1) supersedes the standard Type 2 diabetes code (E11) during pregnancy. Use the O-chapter code for claims during the pregnancy period.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O10",
    code2: "I10",
    type: "mutually_exclusive",
    reason: "Pre-existing hypertension complicating pregnancy (O10) supersedes essential hypertension (I10) during pregnancy. SA coding convention requires the O-chapter code for pregnancy-related encounters.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O10",
    code2: "O11",
    type: "mutually_exclusive",
    reason: "Pre-existing hypertension complicating pregnancy (O10) and pre-existing hypertensive disorder with superimposed proteinuria (O11) — if proteinuria develops, O11 replaces O10 as it captures the progression.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O13",
    code2: "O14",
    type: "mutually_exclusive",
    reason: "Gestational hypertension without proteinuria (O13) and pre-eclampsia (O14, with proteinuria) are mutually exclusive. If proteinuria develops, the diagnosis upgrades to pre-eclampsia (O14).",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O14",
    code2: "O15",
    type: "mutually_exclusive",
    reason: "Pre-eclampsia (O14) and eclampsia (O15) represent severity escalation. If seizures occur, the diagnosis is eclampsia (O15) — coding both implies contradictory staging.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O44",
    code2: "O45",
    type: "mutually_exclusive",
    reason: "Placenta praevia (O44) and premature separation of placenta / abruption (O45) — while both involve placental complications, they are distinct pathologies. Dual coding requires explicit documentation of both conditions.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O24.4",
    code2: "O24.0",
    type: "mutually_exclusive",
    reason: "Gestational diabetes (O24.4) and pre-existing Type 1 diabetes in pregnancy (O24.0) are mutually exclusive — the diabetes is either gestational (developing during pregnancy) or pre-existing Type 1.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O24.4",
    code2: "O24.1",
    type: "mutually_exclusive",
    reason: "Gestational diabetes (O24.4) and pre-existing Type 2 diabetes in pregnancy (O24.1) are mutually exclusive — the diabetes is either newly developed during pregnancy or was pre-existing.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O00",
    code2: "O36",
    type: "mutually_exclusive",
    reason: "Ectopic pregnancy (O00) and maternal care for known or suspected foetal problems (O36) are incompatible. Ectopic pregnancies do not have a viable intrauterine foetus to monitor.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "O02",
    code2: "O60",
    type: "mutually_exclusive",
    reason: "Other abnormal products of conception (O02, including blighted ovum and molar pregnancy) and preterm labour (O60) are incompatible — molar pregnancies do not progress to viable labour.",
    source: "WHO ICD-10 coding conventions; CCSA obstetric coding guidelines",
    category: "icd10_exclusion",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL CROSS-CATEGORY RULES (to reach ~250)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "E10",
    code2: "O24.4",
    type: "mutually_exclusive",
    reason: "Type 1 diabetes (E10) and gestational diabetes (O24.4) are incompatible. Type 1 is a pre-existing autoimmune condition; gestational diabetes develops de novo in pregnancy. Use O24.0 for pre-existing Type 1 in pregnancy.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "E11",
    code2: "O24.4",
    type: "mutually_exclusive",
    reason: "Type 2 diabetes (E11) and gestational diabetes (O24.4) are incompatible. If diabetes was pre-existing, use O24.1. Gestational diabetes is a new-onset condition during pregnancy.",
    source: "WHO ICD-10 coding conventions; CMS maternity CDL guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "I21.0",
    code2: "I21.1",
    type: "mutually_exclusive",
    reason: "Acute transmural MI of anterior wall (I21.0) and acute transmural MI of inferior wall (I21.1) — a single MI event has one primary territory. Dual wall involvement requires specific multi-vessel coding documentation.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for AMI",
    category: "icd10_exclusion",
  },
  {
    code1: "J45.0",
    code2: "J46",
    type: "mutually_exclusive",
    reason: "Predominantly allergic asthma (J45.0, chronic) and status asthmaticus (J46, acute severe) — during an acute severe episode, J46 is the active code. The chronic classification should not be dual-coded with the acute emergency code.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for asthma (CDL 3)",
    category: "icd10_exclusion",
  },
  {
    code1: "N18.1",
    code2: "N18.5",
    type: "mutually_exclusive",
    reason: "Chronic kidney disease stage 1 (N18.1) and CKD stage 5 (N18.5) are mutually exclusive severity stages. A patient has one CKD stage at a time based on GFR measurement.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for renal disease (CDL 8)",
    category: "icd10_exclusion",
  },
  {
    code1: "N18.2",
    code2: "N18.4",
    type: "mutually_exclusive",
    reason: "Chronic kidney disease stage 2 (N18.2) and CKD stage 4 (N18.4) cannot coexist — a patient occupies one CKD stage at any given time based on kidney function.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for renal disease",
    category: "icd10_exclusion",
  },
  {
    code1: "K70.3",
    code2: "K74",
    type: "mutually_exclusive",
    reason: "Alcoholic cirrhosis of liver (K70.3) and fibrosis and cirrhosis of liver (K74, unspecified aetiology) — if the cirrhosis is known to be alcoholic, the specific code K70.3 supersedes the unspecified K74.",
    source: "WHO ICD-10 coding conventions; CCSA coding standards",
    category: "specificity_conflict",
  },
  {
    code1: "C50",
    code2: "D24",
    type: "mutually_exclusive",
    reason: "Malignant neoplasm of breast (C50) and benign neoplasm of breast (D24) at the same site — a breast lesion is either malignant or benign. If malignancy is confirmed, the benign code no longer applies to that lesion.",
    source: "WHO ICD-10 coding conventions; CCSA oncology coding guidelines",
    category: "icd10_exclusion",
  },
  {
    code1: "F10.3",
    code2: "F10.4",
    type: "mutually_exclusive",
    reason: "Alcohol withdrawal state (F10.3) and alcohol withdrawal state with delirium (F10.4) — F10.4 supersedes F10.3 when delirium is present. Only one withdrawal severity should be coded.",
    source: "WHO ICD-10 coding conventions; HPCSA clinical coding standards",
    category: "mental_health_overlap",
  },
  {
    code1: "G40.3",
    code2: "G40.4",
    type: "mutually_exclusive",
    reason: "Generalised idiopathic epilepsy (G40.3) and other generalised epilepsy (G40.4) — only one epilepsy subtype classification should apply per patient. Dual coding suggests diagnostic uncertainty requiring clarification.",
    source: "WHO ICD-10 coding conventions; CMS CDL guidelines for epilepsy (CDL 9)",
    category: "icd10_exclusion",
  },
];
