// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Tariff-Diagnosis Mismatch Rules — South African Healthcare Claims
// CCSA 4-digit tariff codes paired with clinically inappropriate ICD-10 diagnoses
// ~200 rules across 11 clinical disciplines
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import type { CodePairViolation } from "./types";

export const TARIFF_DIAGNOSIS_MISMATCHES: CodePairViolation[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 1. GENDER MISMATCHES — Procedures on wrong gender (~30)
  // Gynaecology procedures with male diagnoses, urology with female-only, etc.
  // ═══════════════════════════════════════════════════════════════════════════

  // — Gynaecology procedures (1500-1700) with male diagnoses —
  {
    code1: "1500",
    code2: "N40",
    type: "never_together",
    reason: "Diagnostic hysteroscopy (1500) is a gynaecological procedure that cannot be performed on a male patient. N40 (benign prostatic hyperplasia) is a male-only diagnosis, indicating a gender-procedure mismatch.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1500",
    code2: "N41",
    type: "never_together",
    reason: "Diagnostic hysteroscopy (1500) is a female-only procedure. N41 (inflammatory diseases of prostate) is a male diagnosis. This combination indicates a coding error or gender mismatch.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1500",
    code2: "C61",
    type: "never_together",
    reason: "Diagnostic hysteroscopy (1500) cannot be indicated for prostate cancer (C61). The procedure involves intrauterine visualisation and is anatomically impossible in males.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1500",
    code2: "C62",
    type: "never_together",
    reason: "Diagnostic hysteroscopy (1500) is a gynaecological procedure incompatible with testicular cancer (C62), a male-only diagnosis.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1600",
    code2: "N40",
    type: "never_together",
    reason: "Hysterectomy (1600) is the surgical removal of the uterus and cannot be performed on a male patient. N40 (BPH) is a male-only prostatic diagnosis — clear gender mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1600",
    code2: "C61",
    type: "never_together",
    reason: "Hysterectomy (1600) removes the uterus and is anatomically impossible in males. C61 (prostate cancer) is a male-only malignancy. This represents a definitive gender-procedure mismatch.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1600",
    code2: "C62",
    type: "never_together",
    reason: "Hysterectomy (1600) is a female-only procedure. Testicular cancer (C62) is a male-only diagnosis. The combination is anatomically impossible.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1650",
    code2: "N40",
    type: "never_together",
    reason: "Oophorectomy (1650) removes the ovaries, a female-only organ. N40 (BPH) is a male prostatic condition. This pairing is a clear gender mismatch.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1650",
    code2: "C61",
    type: "never_together",
    reason: "Oophorectomy (1650) is a female gynaecological procedure. Prostate cancer (C61) is male-only. The tariff-diagnosis pair is anatomically impossible.",
    source: "CCSA v11 discipline-diagnosis validation; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1700",
    code2: "N40",
    type: "never_together",
    reason: "Caesarean section (1700) is an obstetric delivery procedure exclusive to female patients. N40 (BPH) is a male diagnosis — this is a definitive gender mismatch.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1700",
    code2: "C61",
    type: "never_together",
    reason: "C-section (1700) is a female obstetric procedure. Prostate cancer (C61) is a male-only malignancy. Anatomically impossible combination.",
    source: "CCSA v11 gender validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1700",
    code2: "C63",
    type: "never_together",
    reason: "C-section (1700) is an obstetric procedure for females. C63 (malignant neoplasm of other male genital organs) is male-only. Clear gender coding error.",
    source: "CCSA v11 discipline-diagnosis validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Urology procedures (1400-1450) with female-only diagnoses —
  {
    code1: "1410",
    code2: "N80",
    type: "never_together",
    reason: "Prostatectomy (1410) is a male-only urological procedure. N80 (endometriosis) is a female-only condition involving ectopic endometrial tissue. Gender mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1410",
    code2: "N83",
    type: "never_together",
    reason: "Prostatectomy (1410) is a male-only procedure. N83 (noninflammatory disorders of ovary) is a female-only diagnosis. This combination is anatomically impossible.",
    source: "CCSA v11 gender validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1410",
    code2: "C56",
    type: "never_together",
    reason: "Prostatectomy (1410) is exclusive to male patients. Ovarian cancer (C56) is a female-only malignancy. This pairing indicates a coding error.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1410",
    code2: "N92",
    type: "never_together",
    reason: "Prostatectomy (1410) is a male urological procedure. N92 (excessive or frequent menstruation) is a female-only gynaecological diagnosis. Clear gender mismatch.",
    source: "CCSA v11 gender validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1420",
    code2: "N80",
    type: "never_together",
    reason: "TURP (1420) is a transurethral prostate resection — male-only procedure. N80 (endometriosis) is a female-only condition. Anatomically impossible pairing.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1420",
    code2: "C51",
    type: "never_together",
    reason: "TURP (1420) is a male prostate procedure. C51 (vulvar cancer) is a female-only malignancy. Gender mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1420",
    code2: "C53",
    type: "never_together",
    reason: "TURP (1420) is a male urological procedure. C53 (cervical cancer) is a female-only malignancy. Definitive gender-procedure mismatch.",
    source: "CCSA v11 gender validation; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1450",
    code2: "N98",
    type: "never_together",
    reason: "Orchidectomy (1450) removes the testis, a male-only organ. N98 (complications associated with artificial fertilisation) with this procedure is a gender mismatch if claimed for a female patient.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1450",
    code2: "C58",
    type: "never_together",
    reason: "Orchidectomy (1450) is a male-only procedure. C58 (placental cancer) is a female-only obstetric malignancy. This combination is anatomically impossible.",
    source: "CCSA v11 gender validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },

  // — Mammography/imaging with wrong-gender diagnoses —
  {
    code1: "3751",
    code2: "C61",
    type: "never_together",
    reason: "Bilateral mammography (3751) is a breast screening procedure for females. C61 (prostate cancer) is a male-only diagnosis, indicating a gender coding error on the claim.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3751",
    code2: "N40",
    type: "never_together",
    reason: "Bilateral mammography (3751) is a female breast imaging procedure. N40 (BPH) is a male prostate diagnosis. Gender mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3752",
    code2: "C61",
    type: "never_together",
    reason: "Unilateral mammography (3752) is a breast imaging procedure. C61 (prostate cancer) is male-only. Gender mismatch on claim.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4090",
    code2: "N83",
    type: "never_together",
    reason: "PSA test (4090) is a prostate-specific antigen test for males. N83 (ovarian disorders) is a female-only diagnosis. PSA has no clinical relevance in ovarian pathology.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4090",
    code2: "C56",
    type: "never_together",
    reason: "PSA test (4090) measures prostate-specific antigen. C56 (ovarian cancer) is a female-only malignancy. PSA is not indicated for ovarian pathology.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4090",
    code2: "N80",
    type: "never_together",
    reason: "PSA test (4090) is male-specific. N80 (endometriosis) is a female-only condition. No clinical indication for PSA with endometriosis.",
    source: "CCSA v11 discipline-diagnosis validation; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Obstetric US and Pap smear with male diagnoses —
  {
    code1: "3820",
    code2: "N40",
    type: "never_together",
    reason: "Obstetric ultrasound (3820) is performed during pregnancy on female patients. N40 (BPH) is a male diagnosis. Anatomically impossible combination.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3820",
    code2: "C61",
    type: "never_together",
    reason: "Obstetric ultrasound (3820) is a pregnancy-related imaging procedure for female patients. C61 (prostate cancer) is male-only. Clear gender mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4270",
    code2: "N40",
    type: "never_together",
    reason: "Pap smear (4270) is a cervical cytology test for females. N40 (BPH) is a male prostate diagnosis. Gender mismatch — males do not have a cervix.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4270",
    code2: "C62",
    type: "never_together",
    reason: "Pap smear (4270) is a female cervical screening test. C62 (testicular cancer) is a male-only malignancy. Definitive gender-procedure mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Testicular US with female diagnoses —
  {
    code1: "3860",
    code2: "N83",
    type: "never_together",
    reason: "Testicular ultrasound (3860) images the male testes. N83 (ovarian disorders) is a female-only diagnosis. Anatomically impossible combination.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3860",
    code2: "C56",
    type: "never_together",
    reason: "Testicular ultrasound (3860) is a male-only imaging procedure. C56 (ovarian cancer) is a female-only malignancy. Gender mismatch.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. OPHTHALMOLOGY PROCEDURES WITH NON-EYE DIAGNOSES (~15)
  // Cataract surgery, retinal surgery, glaucoma surgery, intravitreal injection
  // ═══════════════════════════════════════════════════════════════════════════

  // — Cataract surgery (2200) —
  {
    code1: "2200",
    code2: "M54.5",
    type: "never_together",
    reason: "Cataract surgery (2200) is an ophthalmic procedure. M54.5 (low back pain) is a musculoskeletal diagnosis with no clinical relevance to lens pathology. An eye diagnosis (H25-H26) is required.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "J06.9",
    type: "never_together",
    reason: "Cataract surgery (2200) treats lens opacity. J06.9 (acute upper respiratory infection) is unrelated — cataract surgery is never indicated for URTI.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "E11.9",
    type: "never_together",
    reason: "Cataract surgery (2200) requires a primary ophthalmic diagnosis (H25/H26). E11.9 (Type 2 diabetes without complications) alone does not justify cataract surgery — diabetic cataract requires H28.0 or H25/H26 as the primary code with E11 as secondary.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "K29.7",
    type: "never_together",
    reason: "Cataract surgery (2200) is an ophthalmic procedure unrelated to gastritis (K29.7). No clinical pathway connects lens surgery to gastric pathology.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "N39.0",
    type: "never_together",
    reason: "Cataract surgery (2200) treats lens opacity. N39.0 (urinary tract infection) is a genitourinary diagnosis with no relevance to ophthalmic surgery.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "I10",
    type: "never_together",
    reason: "Cataract surgery (2200) requires a primary ophthalmic diagnosis. I10 (essential hypertension) alone does not indicate cataract pathology — hypertension may be a comorbidity but not the surgical indication.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "F32",
    type: "never_together",
    reason: "Cataract surgery (2200) is not clinically indicated for major depressive disorder (F32). An ophthalmic diagnosis must be primary for lens surgery.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2200",
    code2: "L30",
    type: "never_together",
    reason: "Cataract surgery (2200) is an intraocular procedure. L30 (dermatitis) is a skin condition with no clinical connection to lens pathology.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Retinal surgery (2240) —
  {
    code1: "2240",
    code2: "M54.5",
    type: "never_together",
    reason: "Retinal surgery (2240) treats retinal detachment/pathology. M54.5 (low back pain) is a musculoskeletal diagnosis unrelated to retinal conditions. Requires H33-H35 diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2240",
    code2: "K29.7",
    type: "never_together",
    reason: "Retinal surgery (2240) addresses retinal pathology. K29.7 (gastritis) has no clinical relevance to retinal disease. An ophthalmic diagnosis is required as primary.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — Glaucoma surgery (2220) —
  {
    code1: "2220",
    code2: "N39.0",
    type: "never_together",
    reason: "Glaucoma surgery (2220) reduces intraocular pressure. N39.0 (UTI) is a genitourinary diagnosis with no connection to glaucoma. Requires H40 diagnosis as primary.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2220",
    code2: "J06.9",
    type: "never_together",
    reason: "Glaucoma surgery (2220) is an ophthalmic procedure for raised IOP. J06.9 (URTI) is an unrelated respiratory diagnosis. Ophthalmic diagnosis (H40) must be primary.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2220",
    code2: "L30",
    type: "never_together",
    reason: "Glaucoma surgery (2220) treats elevated intraocular pressure. L30 (dermatitis) is a dermatological condition with no relevance to ophthalmic surgery.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — Intravitreal injection (2250) —
  {
    code1: "2250",
    code2: "I10",
    type: "never_together",
    reason: "Intravitreal injection (2250) delivers medication into the vitreous for retinal conditions. I10 (hypertension) alone is not an indication — requires a retinal diagnosis such as H35.3 (macular degeneration) or H36.0 (diabetic retinopathy).",
    source: "CCSA v11 discipline-diagnosis validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2250",
    code2: "F32",
    type: "never_together",
    reason: "Intravitreal injection (2250) is an ophthalmic procedure. F32 (depressive episode) has no clinical link to retinal pathology requiring intravitreal medication.",
    source: "BHF clinical appropriateness rules; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. ENT PROCEDURES WITH NON-EAR/NOSE/THROAT DIAGNOSES (~10)
  // Tonsillectomy, septoplasty, myringotomy, FESS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "2300",
    code2: "I10",
    type: "never_together",
    reason: "Tonsillectomy (2300) removes the tonsils for chronic tonsillitis or sleep apnoea. I10 (hypertension) alone is not an indication for tonsillectomy. Requires J35 (chronic tonsillitis) or G47.3 (sleep apnoea).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2300",
    code2: "E11",
    type: "never_together",
    reason: "Tonsillectomy (2300) is an ENT procedure. E11 (Type 2 diabetes) alone is not a clinical indication for tonsil removal. ENT diagnosis required as primary.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2300",
    code2: "M54.5",
    type: "never_together",
    reason: "Tonsillectomy (2300) is an ENT surgical procedure. M54.5 (low back pain) is a musculoskeletal diagnosis unrelated to tonsillar pathology.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2300",
    code2: "L30",
    type: "never_together",
    reason: "Tonsillectomy (2300) treats tonsillar disease. L30 (dermatitis) is a dermatological condition with no clinical connection to tonsillectomy indications.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2310",
    code2: "K29.7",
    type: "never_together",
    reason: "Septoplasty (2310) corrects nasal septal deviation. K29.7 (gastritis) is a GI diagnosis unrelated to nasal anatomy. Requires J34.2 (deviated septum) or R06.8 (nasal obstruction).",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2310",
    code2: "N39.0",
    type: "never_together",
    reason: "Septoplasty (2310) is a nasal surgical procedure. N39.0 (UTI) is a genitourinary diagnosis with no relevance to nasal septal pathology.",
    source: "CCSA v11 discipline-diagnosis validation; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2310",
    code2: "F32",
    type: "never_together",
    reason: "Septoplasty (2310) corrects nasal septal deviation. F32 (depressive episode) is a psychiatric diagnosis and not an indication for nasal surgery.",
    source: "CMS clinical edit guidelines; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2330",
    code2: "M54.5",
    type: "never_together",
    reason: "Myringotomy (2330) is an ear drum incision for otitis media. M54.5 (low back pain) has no relevance to middle ear pathology. Requires H65/H66 diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2330",
    code2: "E11",
    type: "never_together",
    reason: "Myringotomy (2330) treats middle ear effusion/infection. E11 (Type 2 diabetes) alone is not an indication for ear surgery. An otological diagnosis is required.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2320",
    code2: "N39.0",
    type: "never_together",
    reason: "FESS (2320) is functional endoscopic sinus surgery for sinusitis. N39.0 (UTI) is a genitourinary diagnosis unrelated to sinus pathology. Requires J32 (chronic sinusitis) or J33 (nasal polyps).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. ORTHOPAEDIC PROCEDURES WITH NON-MSK DIAGNOSES (~15)
  // Arthroscopy, joint replacement, fracture fixation, spinal fusion, CTS release
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "0800",
    code2: "F32",
    type: "never_together",
    reason: "Arthroscopy (0800) is an orthopaedic diagnostic/therapeutic procedure. F32 (depressive episode) is a psychiatric diagnosis with no indication for joint arthroscopy. Requires M-code or S-code as primary.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0800",
    code2: "J06.9",
    type: "never_together",
    reason: "Arthroscopy (0800) is an orthopaedic procedure. J06.9 (URTI) is an acute respiratory infection unrelated to joint pathology. Musculoskeletal diagnosis required.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0800",
    code2: "E11",
    type: "never_together",
    reason: "Arthroscopy (0800) requires a musculoskeletal primary diagnosis. E11 (Type 2 diabetes) alone is not an indication for joint arthroscopy.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0800",
    code2: "N39.0",
    type: "never_together",
    reason: "Arthroscopy (0800) is an orthopaedic procedure. N39.0 (UTI) is a genitourinary diagnosis with no clinical connection to joint pathology.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0780",
    code2: "J06.9",
    type: "never_together",
    reason: "Joint replacement (0780) is major orthopaedic surgery for severe joint disease. J06.9 (URTI) is not a clinical indication — requires M16/M17 (osteoarthritis) or traumatic joint destruction.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0780",
    code2: "I10",
    type: "never_together",
    reason: "Joint replacement (0780) requires a primary musculoskeletal diagnosis (M16/M17 osteoarthritis, M87 osteonecrosis, etc.). I10 (hypertension) alone does not justify major joint surgery.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0780",
    code2: "F32",
    type: "never_together",
    reason: "Joint replacement (0780) is an orthopaedic procedure for end-stage joint disease. F32 (depression) is a psychiatric diagnosis, not an orthopaedic surgical indication.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0760",
    code2: "E11",
    type: "never_together",
    reason: "Fracture fixation (0760) requires a trauma/fracture code (S-codes). E11 (Type 2 diabetes) alone is not a fracture diagnosis — internal fixation is indicated for bone fractures, not metabolic conditions.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0760",
    code2: "I10",
    type: "never_together",
    reason: "Fracture fixation (0760) requires a fracture S-code (e.g., S52, S72). I10 (hypertension) alone is not an indication for orthopaedic fracture fixation hardware.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0760",
    code2: "K29.7",
    type: "never_together",
    reason: "Fracture fixation (0760) is an orthopaedic procedure requiring trauma codes. K29.7 (gastritis) is a GI diagnosis with no relevance to fracture management.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0825",
    code2: "J06.9",
    type: "never_together",
    reason: "Spinal fusion (0825) is a major orthopaedic procedure for spinal instability or deformity. J06.9 (URTI) is not a spinal diagnosis. Requires M43 (spondylolisthesis), M48 (spinal stenosis), or S-code for spinal fracture.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0825",
    code2: "N39.0",
    type: "never_together",
    reason: "Spinal fusion (0825) requires a spinal diagnosis as primary. N39.0 (UTI) has no clinical connection to spinal fusion indications.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0785",
    code2: "I10",
    type: "never_together",
    reason: "Carpal tunnel release (0785) decompresses the median nerve. I10 (hypertension) alone is not an indication — requires G56.0 (carpal tunnel syndrome) as the primary diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0785",
    code2: "J06.9",
    type: "never_together",
    reason: "Carpal tunnel release (0785) is a nerve decompression procedure. J06.9 (URTI) is an unrelated acute respiratory diagnosis. Must be coded with G56.0.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. CARDIOLOGY PROCEDURES WITH NON-CARDIAC DIAGNOSES (~15)
  // ECG, echocardiogram, stress test, catheterisation, troponin, BNP, Holter
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "0308",
    code2: "L30.9",
    type: "never_together",
    reason: "ECG (0308) is a cardiac investigation. L30.9 (dermatitis, unspecified) is a skin condition with no cardiac relevance. ECG requires a cardiac symptom or diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0308",
    code2: "M54.5",
    type: "never_together",
    reason: "ECG (0308) evaluates cardiac electrical activity. M54.5 (low back pain) alone is not a cardiac indication — chest pain (R07) or cardiac symptoms would be appropriate.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0308",
    code2: "K29.7",
    type: "never_together",
    reason: "ECG (0308) is a cardiac test. K29.7 (gastritis) alone does not justify an ECG unless there is chest pain or cardiac differential, which should be coded.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0310",
    code2: "M54.5",
    type: "never_together",
    reason: "Echocardiogram (0310) evaluates cardiac structure and function. M54.5 (low back pain) is a musculoskeletal diagnosis with no clinical link to cardiac imaging. Requires cardiac diagnosis or symptom code.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0310",
    code2: "J06.9",
    type: "never_together",
    reason: "Echocardiogram (0310) is a cardiac ultrasound. J06.9 (URTI) is not an indication for echocardiography. Cardiac diagnosis (I-code or R00-R03) should be primary.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0312",
    code2: "L30",
    type: "never_together",
    reason: "Cardiac stress test (0312) evaluates myocardial ischaemia. L30 (dermatitis) has no cardiac relevance. Requires cardiac symptom (R07, R00) or I-code diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0312",
    code2: "N39.0",
    type: "never_together",
    reason: "Cardiac stress test (0312) assesses coronary artery disease. N39.0 (UTI) is a genitourinary diagnosis unrelated to cardiac stress testing.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0900",
    code2: "M54.5",
    type: "never_together",
    reason: "Cardiac catheterisation (0900) is an invasive cardiac procedure. M54.5 (low back pain) is not a cardiac indication. Requires I-code or acute coronary syndrome diagnosis.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0900",
    code2: "J06.9",
    type: "never_together",
    reason: "Cardiac catheterisation (0900) is an invasive diagnostic procedure for coronary artery disease. J06.9 (URTI) is not a cardiac indication. Primary diagnosis must be cardiac.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4080",
    code2: "N39.0",
    type: "never_together",
    reason: "Troponin (4080) is a cardiac biomarker for myocardial injury. N39.0 (UTI) is a genitourinary diagnosis with no indication for troponin testing. Requires cardiac symptom or I-code.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4080",
    code2: "M54.5",
    type: "never_together",
    reason: "Troponin (4080) detects myocardial damage. M54.5 (low back pain) alone is not an indication for cardiac troponin testing. Chest pain (R07) or ACS diagnosis required.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4080",
    code2: "J06.9",
    type: "never_together",
    reason: "Troponin (4080) is specific to cardiac injury assessment. J06.9 (URTI) alone does not justify troponin testing — myocarditis or cardiac involvement must be coded separately.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4084",
    code2: "M54.5",
    type: "never_together",
    reason: "BNP/NT-proBNP (4084) is a heart failure biomarker. M54.5 (low back pain) has no relevance to cardiac failure assessment. Requires I50 or cardiac symptom code.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4084",
    code2: "L30",
    type: "never_together",
    reason: "BNP (4084) assesses cardiac failure. L30 (dermatitis) is a dermatological condition with no clinical link to heart failure diagnosis.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0315",
    code2: "K29.7",
    type: "never_together",
    reason: "Holter monitor (0315) records 24-hour cardiac rhythm. K29.7 (gastritis) is a GI diagnosis unrelated to cardiac arrhythmia assessment. Requires R00 (palpitations), I-code, or syncope code.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0315",
    code2: "N39.0",
    type: "never_together",
    reason: "Holter monitor (0315) assesses cardiac rhythm disorders. N39.0 (UTI) is a genitourinary diagnosis with no indication for ambulatory cardiac monitoring.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. PATHOLOGY TESTS WITH UNRELATED DIAGNOSES (~40)
  // HbA1c, HIV viral load, CD4, TSH, PSA, RF, ANA, D-dimer, troponin, lipogram, etc.
  // ═══════════════════════════════════════════════════════════════════════════

  // — HbA1c (4052) —
  {
    code1: "4052",
    code2: "J06.9",
    type: "never_together",
    reason: "HbA1c (4052) measures glycaemic control for diabetes. J06.9 (URTI) alone is not an indication — requires E10-E14 (diabetes) or metabolic/screening diagnosis (Z13.1).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4052",
    code2: "M54.5",
    type: "never_together",
    reason: "HbA1c (4052) is a diabetes monitoring test. M54.5 (low back pain) is a musculoskeletal diagnosis unrelated to glycaemic assessment. Diabetes or metabolic diagnosis required.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4052",
    code2: "L30",
    type: "never_together",
    reason: "HbA1c (4052) monitors long-term blood glucose. L30 (dermatitis) is a skin condition with no clinical indication for HbA1c testing.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — HIV viral load (4211) —
  {
    code1: "4211",
    code2: "M54.5",
    type: "never_together",
    reason: "HIV viral load (4211) quantifies HIV RNA for treatment monitoring. M54.5 (low back pain) is not an HIV-related diagnosis. Requires B20-B24 (HIV disease) or Z21 (asymptomatic HIV).",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4211",
    code2: "K29.7",
    type: "never_together",
    reason: "HIV viral load (4211) is specific to HIV management. K29.7 (gastritis) alone does not justify viral load testing. HIV diagnosis (B20-B24, Z21) must be present.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4211",
    code2: "L30",
    type: "never_together",
    reason: "HIV viral load (4211) monitors HIV treatment response. L30 (dermatitis) alone is not an indication — while HIV can cause dermatological conditions, viral load requires an HIV diagnosis code.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — CD4 count (4210) —
  {
    code1: "4210",
    code2: "M54.5",
    type: "never_together",
    reason: "CD4 count (4210) assesses immune status in HIV patients. M54.5 (low back pain) is not an HIV-related diagnosis. Requires B20-B24 or Z21 diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4210",
    code2: "J06.9",
    type: "never_together",
    reason: "CD4 count (4210) is an HIV immune monitoring test. J06.9 (URTI) alone does not justify CD4 testing without an underlying HIV diagnosis.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4210",
    code2: "I10",
    type: "never_together",
    reason: "CD4 count (4210) measures T-helper lymphocytes for HIV staging. I10 (hypertension) is a cardiovascular diagnosis with no relevance to CD4 monitoring. HIV diagnosis required.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — TSH (4070) —
  {
    code1: "4070",
    code2: "S52",
    type: "never_together",
    reason: "TSH (4070) tests thyroid function. S52 (forearm fracture) is an acute trauma code with no indication for thyroid testing. Requires E00-E07 (thyroid disorder) or Z13.2 (screening).",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4070",
    code2: "M54.5",
    type: "never_together",
    reason: "TSH (4070) assesses thyroid function. M54.5 (low back pain) alone is not a clinical indication for thyroid testing unless thyroid pathology is suspected, which should be coded.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — Rheumatoid factor (4115) —
  {
    code1: "4115",
    code2: "J06.9",
    type: "never_together",
    reason: "Rheumatoid factor (4115) is an autoimmune serology test. J06.9 (URTI) is an acute respiratory infection with no indication for RF testing. Requires M05/M06 (RA) or autoimmune suspicion code.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4115",
    code2: "N39.0",
    type: "never_together",
    reason: "Rheumatoid factor (4115) tests for rheumatoid arthritis. N39.0 (UTI) is a genitourinary diagnosis unrelated to autoimmune serology.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4115",
    code2: "I10",
    type: "never_together",
    reason: "Rheumatoid factor (4115) screens for rheumatoid arthritis. I10 (hypertension) alone is not an indication for autoimmune testing. Musculoskeletal/autoimmune diagnosis required.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — ANA (4111) —
  {
    code1: "4111",
    code2: "S52",
    type: "never_together",
    reason: "ANA (4111) is an autoimmune screening test. S52 (forearm fracture) is an acute trauma code — ANA testing is not indicated for traumatic injuries. Requires autoimmune suspicion diagnosis (M32, M35, etc.).",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4111",
    code2: "S72",
    type: "never_together",
    reason: "ANA (4111) tests for autoimmune conditions. S72 (femur fracture) is acute trauma. Antinuclear antibody testing has no clinical relevance in fracture management.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — D-dimer (4026) —
  {
    code1: "4026",
    code2: "M54.5",
    type: "never_together",
    reason: "D-dimer (4026) screens for venous thromboembolism (VTE) or pulmonary embolism. M54.5 (low back pain) alone is not a VTE suspicion. Requires I26 (PE), I80 (DVT), or R07 (chest pain) as primary.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4026",
    code2: "L30",
    type: "never_together",
    reason: "D-dimer (4026) is indicated for VTE/DIC exclusion. L30 (dermatitis) is a skin condition with no clinical link to thromboembolic disease assessment.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Troponin (4081) —
  {
    code1: "4081",
    code2: "N39.0",
    type: "never_together",
    reason: "High-sensitivity troponin (4081) is specific to cardiac injury. N39.0 (UTI) is a genitourinary diagnosis with no indication for cardiac biomarker testing.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4081",
    code2: "J06.9",
    type: "never_together",
    reason: "High-sensitivity troponin (4081) detects myocardial damage. J06.9 (URTI) alone does not justify troponin testing. Cardiac symptoms (R07, R00) or ACS suspicion must be coded.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Lipogram (4059) —
  {
    code1: "4059",
    code2: "S52",
    type: "never_together",
    reason: "Lipogram (4059) measures cholesterol and triglycerides for cardiovascular risk. S52 (forearm fracture) is acute trauma with no indication for lipid screening.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4059",
    code2: "J06.9",
    type: "never_together",
    reason: "Lipogram (4059) is a metabolic screening test. J06.9 (URTI) is an acute respiratory illness — lipid testing is not indicated during acute infections. Requires E78 (dyslipidaemia) or Z13.6 (screening).",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4059",
    code2: "S72",
    type: "never_together",
    reason: "Lipogram (4059) assesses cardiovascular lipid risk. S72 (femur fracture) is acute trauma — lipid testing is not relevant to fracture management.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — Pap smear (4270) with male diagnoses (pathology context) —
  {
    code1: "4270",
    code2: "C61",
    type: "never_together",
    reason: "Pap smear (4270) is cervical cytology for female patients. C61 (prostate cancer) is a male-only malignancy. Gender mismatch — Pap smears are not performed on males.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },

  // — Semen analysis (4160) with female diagnoses —
  {
    code1: "4160",
    code2: "N80",
    type: "never_together",
    reason: "Semen analysis (4160) is a male fertility test. N80 (endometriosis) is a female-only condition. Gender mismatch — semen analysis requires a male patient.",
    source: "CCSA v11 gender validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4160",
    code2: "N83",
    type: "never_together",
    reason: "Semen analysis (4160) evaluates male fertility. N83 (ovarian disorders) is a female-only diagnosis. Anatomically impossible combination.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4160",
    code2: "C56",
    type: "never_together",
    reason: "Semen analysis (4160) is male-specific. C56 (ovarian cancer) is a female-only malignancy. Clear gender-procedure mismatch.",
    source: "CCSA v11 gender validation; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Pregnancy test (4285) with male diagnoses —
  {
    code1: "4285",
    code2: "N40",
    type: "never_together",
    reason: "Pregnancy test (4285) detects hCG in female patients. N40 (BPH) is a male prostate diagnosis. Males cannot be pregnant — definitive gender mismatch.",
    source: "CCSA v11 gender validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4285",
    code2: "C61",
    type: "never_together",
    reason: "Pregnancy test (4285) is a female-specific test. C61 (prostate cancer) is male-only. Gender mismatch — hCG pregnancy testing is not applicable to males. Note: beta-hCG as a tumour marker uses a different tariff code.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4285",
    code2: "C62",
    type: "never_together",
    reason: "Pregnancy test (4285) is for pregnancy detection in females. C62 (testicular cancer) is male-only. While beta-hCG is used as a tumour marker for testicular cancer, the pregnancy test tariff code should not be used — a separate tumour marker code applies.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — AFP (4123) —
  {
    code1: "4123",
    code2: "M54.5",
    type: "never_together",
    reason: "AFP (4123) is a tumour marker/screening test for hepatocellular carcinoma, germ cell tumours, or prenatal screening. M54.5 (low back pain) has no clinical link to AFP indications.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4123",
    code2: "J06.9",
    type: "never_together",
    reason: "AFP (4123) is indicated for liver cancer screening, germ cell tumours, or prenatal anomaly detection. J06.9 (URTI) has no clinical relevance to AFP testing.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — CA-125 (4121) with male diagnoses —
  {
    code1: "4121",
    code2: "C61",
    type: "never_together",
    reason: "CA-125 (4121) is a tumour marker primarily for ovarian cancer monitoring. C61 (prostate cancer) is a male condition — CA-125 is not indicated for prostate malignancy. PSA (4090) is the appropriate marker.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4121",
    code2: "N40",
    type: "never_together",
    reason: "CA-125 (4121) monitors ovarian/gynaecological malignancies. N40 (BPH) is a male prostate condition. CA-125 has no clinical utility in benign prostatic disease.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4121",
    code2: "C62",
    type: "never_together",
    reason: "CA-125 (4121) is an ovarian cancer marker. C62 (testicular cancer) uses AFP and beta-hCG as tumour markers, not CA-125. Wrong marker-diagnosis combination.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // — Estradiol (4096) —
  {
    code1: "4096",
    code2: "N40",
    type: "never_together",
    reason: "Estradiol (4096) is a female reproductive hormone test. N40 (BPH) is a male prostate condition. Estradiol testing is not indicated for benign prostatic hyperplasia in males.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4096",
    code2: "C61",
    type: "never_together",
    reason: "Estradiol (4096) measures oestrogen levels for fertility/endocrine assessment. C61 (prostate cancer) is not an indication for estradiol testing in standard clinical practice.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // — Testosterone (4103) —
  {
    code1: "4103",
    code2: "N80",
    type: "never_together",
    reason: "Testosterone (4103) in a non-endocrine context with N80 (endometriosis) is a mismatch. Endometriosis is an oestrogen-dependent condition — testosterone testing requires an endocrine diagnosis (E28/E29/E23).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "4103",
    code2: "J06.9",
    type: "never_together",
    reason: "Testosterone (4103) is an endocrine hormone assay. J06.9 (URTI) is an acute respiratory infection with no relevance to testosterone assessment. Requires E29 (testicular dysfunction) or E28 (ovarian dysfunction).",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 7. RADIOLOGY WITH UNRELATED DIAGNOSES (~20)
  // MRI brain, CT abdomen, chest X-ray, mammography, obstetric US, DEXA, CT coronary, MRI knee
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "3951",
    code2: "K29.7",
    type: "never_together",
    reason: "MRI brain (3951) images intracranial structures. K29.7 (gastritis) is a GI diagnosis with no indication for brain MRI. Requires neurological diagnosis (G-code) or intracranial symptom.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3951",
    code2: "N39.0",
    type: "never_together",
    reason: "MRI brain (3951) is a neuroimaging procedure. N39.0 (UTI) is a genitourinary diagnosis unrelated to intracranial pathology.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3951",
    code2: "L30",
    type: "never_together",
    reason: "MRI brain (3951) images the brain and is not indicated for dermatitis (L30). No clinical pathway connects skin conditions to brain MRI.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3920",
    code2: "H65",
    type: "never_together",
    reason: "CT abdomen (3920) images abdominal structures. H65 (otitis media) is an ear condition with no relevance to abdominal imaging. Abdominal/pelvic diagnosis required.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3920",
    code2: "H10",
    type: "never_together",
    reason: "CT abdomen (3920) evaluates abdominal pathology. H10 (conjunctivitis) is an eye condition with no indication for abdominal CT scanning.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3601",
    code2: "N39.0",
    type: "never_together",
    reason: "Chest X-ray (3601) images thoracic structures. N39.0 (UTI) alone is not an indication for chest radiography — CXR is not first-line investigation for urinary tract infections.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3601",
    code2: "L30",
    type: "never_together",
    reason: "Chest X-ray (3601) is a thoracic imaging study. L30 (dermatitis) is a skin condition not requiring chest radiography. Respiratory or cardiac diagnosis needed.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3751",
    code2: "C62",
    type: "never_together",
    reason: "Bilateral mammography (3751) is a female breast imaging procedure. C62 (testicular cancer) is a male-only malignancy. Gender mismatch.",
    source: "BHF clinical appropriateness rules; CCSA v11 gender validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3820",
    code2: "C62",
    type: "never_together",
    reason: "Obstetric ultrasound (3820) is a pregnancy-related scan for female patients. C62 (testicular cancer) is male-only. Obstetric imaging cannot be performed on males.",
    source: "CCSA v11 gender validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3820",
    code2: "N39.0",
    type: "never_together",
    reason: "Obstetric ultrasound (3820) is specific to pregnancy monitoring. N39.0 (UTI) in a non-pregnant patient does not justify obstetric ultrasound. Requires O-code (pregnancy) or Z33 (pregnant state).",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3705",
    code2: "S52",
    type: "never_together",
    reason: "Bone density/DEXA scan (3705) assesses osteoporosis risk. S52 (forearm fracture) is an acute trauma code — DEXA is not indicated during acute fracture management. Requires M80/M81 (osteoporosis) or Z87.3 (history of fracture).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3705",
    code2: "S72",
    type: "never_together",
    reason: "DEXA scan (3705) measures bone mineral density for osteoporosis. S72 (femur fracture) as the acute fracture diagnosis is not appropriate for a DEXA scan during acute management. DEXA should be performed after fracture management with M80/M81 as indication.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3950",
    code2: "M54.5",
    type: "never_together",
    reason: "CT coronary angiography (3950) evaluates coronary artery disease. M54.5 (low back pain) is a musculoskeletal diagnosis with no cardiac relevance. Requires I-code or R07 (chest pain).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3950",
    code2: "J06.9",
    type: "never_together",
    reason: "CT coronary angiography (3950) is a cardiac imaging study. J06.9 (URTI) is not a cardiac indication. Requires coronary artery disease suspicion or cardiac symptom diagnosis.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3950",
    code2: "N39.0",
    type: "never_together",
    reason: "CT coronary (3950) evaluates coronary arteries. N39.0 (UTI) is a genitourinary diagnosis unrelated to cardiac imaging. Cardiac diagnosis required.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3965",
    code2: "I10",
    type: "never_together",
    reason: "MRI knee (3965) images the knee joint. I10 (essential hypertension) alone is not an indication for knee MRI. Requires M-code (knee pathology) or S83 (knee injury).",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3965",
    code2: "J06.9",
    type: "never_together",
    reason: "MRI knee (3965) is a musculoskeletal imaging study. J06.9 (URTI) has no clinical link to knee pathology. Musculoskeletal diagnosis required.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3965",
    code2: "F32",
    type: "never_together",
    reason: "MRI knee (3965) images knee joint structures. F32 (depressive episode) is a psychiatric diagnosis unrelated to knee imaging. MSK diagnosis required as primary.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "3965",
    code2: "E11",
    type: "never_together",
    reason: "MRI knee (3965) is a musculoskeletal investigation. E11 (Type 2 diabetes) alone does not justify knee MRI. While diabetes can cause joint complications, the joint diagnosis must be coded as primary.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 8. SURGICAL PROCEDURES WITH MEDICAL-ONLY DIAGNOSES (~15)
  // Appendicectomy, cholecystectomy, hernia repair, C-section, tonsillectomy, TURP
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "1106",
    code2: "I10",
    type: "never_together",
    reason: "Appendicectomy (1106) requires an appendicitis diagnosis (K35/K36/K37). I10 (hypertension) alone is not a surgical indication for appendix removal.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1106",
    code2: "E11",
    type: "never_together",
    reason: "Appendicectomy (1106) is indicated for appendicitis (K35-K37). E11 (Type 2 diabetes) alone does not justify appendix surgery. Surgical indication must be the primary diagnosis.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1105",
    code2: "I10",
    type: "never_together",
    reason: "Cholecystectomy (1105) removes the gallbladder. I10 (hypertension) alone is not an indication — requires K80 (cholelithiasis) or K81 (cholecystitis) as primary diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1105",
    code2: "M54.5",
    type: "never_together",
    reason: "Cholecystectomy (1105) is indicated for gallbladder disease. M54.5 (low back pain) is a musculoskeletal diagnosis unrelated to gallbladder pathology. Requires K80/K81.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1107",
    code2: "J06.9",
    type: "never_together",
    reason: "Hernia repair (1107) requires a hernia diagnosis (K40-K46). J06.9 (URTI) is not a surgical indication for hernia repair.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1107",
    code2: "E11",
    type: "never_together",
    reason: "Hernia repair (1107) is indicated for K40-K46 (hernia diagnoses). E11 (diabetes) alone does not justify hernia surgery. Hernia diagnosis must be primary.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1700",
    code2: "J06.9",
    type: "never_together",
    reason: "Caesarean section (1700) requires an obstetric indication (O-code). J06.9 (URTI) alone is not a reason for operative delivery. Must have obstetric diagnosis such as O82 (C-section delivery).",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1700",
    code2: "I10",
    type: "never_together",
    reason: "Caesarean section (1700) requires an obstetric indication. I10 (hypertension) alone does not justify C-section — pre-eclampsia would need O14, not I10 as primary. O-code must be present.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1700",
    code2: "M54.5",
    type: "never_together",
    reason: "C-section (1700) is an obstetric delivery procedure. M54.5 (low back pain) is not an obstetric indication. Requires O-code as primary diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "2300",
    code2: "K29.7",
    type: "never_together",
    reason: "Tonsillectomy (2300) requires J35 (chronic tonsillitis) or G47.3 (sleep apnoea). K29.7 (gastritis) is a GI diagnosis unrelated to tonsillectomy indications.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1410",
    code2: "J06.9",
    type: "never_together",
    reason: "TURP/prostatectomy (1410) requires N40 (BPH) or C61 (prostate cancer) as primary diagnosis. J06.9 (URTI) is not a urological surgical indication.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1410",
    code2: "I10",
    type: "never_together",
    reason: "Prostatectomy (1410) is a urological surgical procedure for BPH (N40) or prostate cancer (C61). I10 (hypertension) alone does not justify prostate surgery.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "1410",
    code2: "M54.5",
    type: "never_together",
    reason: "Prostatectomy (1410) removes prostate tissue. M54.5 (low back pain) is musculoskeletal and not a prostate diagnosis. Requires N40 or C61.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 9. ALLIED HEALTH WITH INAPPROPRIATE PRIMARY DIAGNOSES (~15)
  // Physiotherapy, psychology, dietetics, speech therapy, occupational therapy
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "6001",
    code2: "E11.9",
    type: "never_together",
    reason: "Physiotherapy (6001) requires a musculoskeletal or neurological diagnosis. E11.9 (Type 2 diabetes without complications) alone is not a physiotherapy indication. Diabetic neuropathy (E11.4+G63.2) or MSK complication must be coded.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6001",
    code2: "I10",
    type: "never_together",
    reason: "Physiotherapy (6001) treats movement disorders, MSK, and neurological conditions. I10 (essential hypertension) alone is not a physiotherapy indication. Requires M-code, G-code, or S-code.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6001",
    code2: "K29.7",
    type: "never_together",
    reason: "Physiotherapy (6001) addresses musculoskeletal and neurological conditions. K29.7 (gastritis) is a GI diagnosis with no physiotherapy indication.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6400",
    code2: "I10",
    type: "never_together",
    reason: "Psychology consultation (6400) requires a mental health or psychosocial diagnosis. I10 (hypertension) alone is not a psychology indication. Requires F-code (mental disorder) or Z-code (psychosocial factor).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6400",
    code2: "E11",
    type: "never_together",
    reason: "Psychology (6400) treats mental and behavioural conditions. E11 (Type 2 diabetes) alone is not a psychology indication. If diabetes-related distress, F54 or Z-code must be coded.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6400",
    code2: "M54.5",
    type: "never_together",
    reason: "Psychology (6400) requires a mental health diagnosis as primary. M54.5 (low back pain) alone is a musculoskeletal diagnosis. While chronic pain has psychological components, the F-code or Z-code must be present.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6300",
    code2: "M54.5",
    type: "never_together",
    reason: "Dietetics consultation (6300) requires a metabolic or nutritional diagnosis. M54.5 (low back pain) is musculoskeletal and not a dietetics indication. Requires E-code (metabolic), E40-E68 (nutrition), or chronic disease management diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6300",
    code2: "S52",
    type: "never_together",
    reason: "Dietetics (6300) addresses nutritional and metabolic conditions. S52 (forearm fracture) is acute trauma with no primary dietetics indication.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6300",
    code2: "J06.9",
    type: "never_together",
    reason: "Dietetics consultation (6300) requires a nutritional or metabolic diagnosis. J06.9 (URTI) is an acute infection with no dietetics indication. Requires E-code or chronic disease code.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6200",
    code2: "M54.5",
    type: "never_together",
    reason: "Speech therapy (6200) treats communication, swallowing, and voice disorders. M54.5 (low back pain) has no relevance to speech/swallowing pathology. Requires R13 (dysphagia), R47 (speech disturbance), or F80 (speech development).",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6200",
    code2: "E11",
    type: "never_together",
    reason: "Speech therapy (6200) addresses communication and swallowing disorders. E11 (Type 2 diabetes) alone is not a speech therapy indication.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6200",
    code2: "I10",
    type: "never_together",
    reason: "Speech therapy (6200) treats speech, language, and swallowing disorders. I10 (hypertension) alone is not an indication. Post-stroke dysphasia requires I63+R47 coding, not I10 alone.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6100",
    code2: "I10",
    type: "never_together",
    reason: "Occupational therapy (6100) treats functional, rehabilitation, and developmental disorders. I10 (hypertension) alone is not an OT indication. Requires functional or rehabilitation diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6100",
    code2: "J06.9",
    type: "never_together",
    reason: "Occupational therapy (6100) addresses functional ability and rehabilitation. J06.9 (URTI) is an acute respiratory infection with no OT indication.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 10. DENTAL PROCEDURES WITH NON-DENTAL DIAGNOSES (~15)
  // Root canal, extraction, crown, scaling, orthodontics, periodontal surgery
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "8300",
    code2: "I10",
    type: "never_together",
    reason: "Root canal treatment (8300) is a dental endodontic procedure. I10 (hypertension) alone is not a dental indication. Requires dental diagnosis K04 (pulp/periapical disease) or K00-K14 dental code.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8300",
    code2: "E11",
    type: "never_together",
    reason: "Root canal (8300) treats dental pulp pathology. E11 (Type 2 diabetes) alone is not a dental diagnosis. Requires K04 (diseases of pulp and periapical tissues) as primary.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8300",
    code2: "M54.5",
    type: "never_together",
    reason: "Root canal treatment (8300) addresses dental pulp disease. M54.5 (low back pain) is musculoskeletal and completely unrelated to dental pathology.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8601",
    code2: "I10",
    type: "never_together",
    reason: "Dental extraction (8601) requires a dental diagnosis. I10 (hypertension) alone does not justify tooth extraction. Requires K-code dental diagnosis (K00-K14).",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8601",
    code2: "J06.9",
    type: "never_together",
    reason: "Dental extraction (8601) removes teeth for dental indications. J06.9 (URTI) is a respiratory diagnosis unrelated to dental extraction. Dental K-code required.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8230",
    code2: "E11",
    type: "never_together",
    reason: "Crown preparation (8230) is a dental restorative procedure. E11 (Type 2 diabetes) alone is not a dental indication. Requires K02 (dental caries) or K03 (tooth wear) as primary.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8230",
    code2: "M54.5",
    type: "never_together",
    reason: "Crown (8230) is a dental restoration. M54.5 (low back pain) has no dental relevance. Dental diagnosis K02/K03/K08 must be primary.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8155",
    code2: "I10",
    type: "never_together",
    reason: "Dental scaling (8155) is a periodontal cleaning procedure. I10 (hypertension) alone is not a dental indication. Requires K05 (gingivitis/periodontitis) or K03 as primary.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8155",
    code2: "N39.0",
    type: "never_together",
    reason: "Dental scaling (8155) treats periodontal disease. N39.0 (UTI) is a genitourinary diagnosis unrelated to dental cleaning. Requires K05 dental diagnosis.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8500",
    code2: "E11",
    type: "never_together",
    reason: "Orthodontic treatment (8500) corrects dental malocclusion. E11 (Type 2 diabetes) is not an orthodontic indication. Requires K07 (dentofacial anomalies) as primary.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8500",
    code2: "I10",
    type: "never_together",
    reason: "Orthodontics (8500) treats dental alignment and bite disorders. I10 (hypertension) has no relevance to orthodontic treatment. K07 diagnosis required.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8500",
    code2: "M54.5",
    type: "never_together",
    reason: "Orthodontic treatment (8500) is a dental discipline procedure. M54.5 (low back pain) is musculoskeletal and unrelated to dentofacial anomalies.",
    source: "BHF clinical appropriateness rules; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8185",
    code2: "J06.9",
    type: "never_together",
    reason: "Periodontal surgery (8185) treats advanced gum disease. J06.9 (URTI) is a respiratory diagnosis unrelated to periodontal surgical indications. Requires K05 (periodontitis).",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "8185",
    code2: "F32",
    type: "never_together",
    reason: "Periodontal surgery (8185) addresses advanced periodontal disease. F32 (depressive episode) is a psychiatric diagnosis not indicating gum surgery. K05 diagnosis required.",
    source: "BHF clinical appropriateness rules; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 11. MENTAL HEALTH PROCEDURES WITH NON-MENTAL DIAGNOSES (~10)
  // Psychiatric consultation, ECT, psychometric testing, psychiatric admission
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code1: "0181",
    code2: "M54.5",
    type: "never_together",
    reason: "Psychiatric consultation (0181) requires a mental health diagnosis. M54.5 (low back pain) is musculoskeletal and not a psychiatric indication. Requires F-code or Z-code psychosocial diagnosis.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0181",
    code2: "K29.7",
    type: "never_together",
    reason: "Psychiatric consultation (0181) is for mental health assessment. K29.7 (gastritis) is a GI diagnosis with no psychiatric indication. F-code must be primary.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0181",
    code2: "S52",
    type: "never_together",
    reason: "Psychiatric consultation (0181) evaluates mental health. S52 (forearm fracture) is acute trauma — not a psychiatric diagnosis. Unless adjustment disorder (F43) is coded, S52 alone does not justify psychiatry.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0181",
    code2: "I10",
    type: "never_together",
    reason: "Psychiatric consultation (0181) requires a mental health diagnosis as primary. I10 (hypertension) alone is a cardiovascular diagnosis, not a psychiatric one.",
    source: "CCSA v11 discipline-diagnosis validation; CMS clinical edit guidelines",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0185",
    code2: "I10",
    type: "never_together",
    reason: "ECT (0185) is indicated for severe refractory depression, catatonia, or psychosis. I10 (hypertension) is not a psychiatric diagnosis and does not justify ECT. Requires F20 (schizophrenia), F31 (bipolar), F32.3 (severe depression), or F44 (catatonia).",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0185",
    code2: "M54.5",
    type: "never_together",
    reason: "ECT (0185) treats severe psychiatric conditions. M54.5 (low back pain) is a musculoskeletal diagnosis — ECT is never indicated for pain. Requires F-code for psychotic or severe mood disorder.",
    source: "CMS clinical edit guidelines; GEMS clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6420",
    code2: "I10",
    type: "never_together",
    reason: "Psychometric testing (6420) assesses cognitive and psychological functioning. I10 (hypertension) alone is not an indication for psychometric evaluation. Requires F-code, R41 (cognitive symptoms), or Z-code.",
    source: "CCSA v11 discipline-diagnosis validation; BHF clinical appropriateness rules",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "6420",
    code2: "K29.7",
    type: "never_together",
    reason: "Psychometric testing (6420) evaluates psychological and cognitive function. K29.7 (gastritis) is a GI diagnosis with no relevance to psychometric assessment.",
    source: "CMS clinical edit guidelines; Discovery clinical edits",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0186",
    code2: "M54.5",
    type: "never_together",
    reason: "Psychiatric admission (0186) requires an F-code psychiatric diagnosis. M54.5 (low back pain) is musculoskeletal and does not justify psychiatric hospitalisation.",
    source: "BHF clinical appropriateness rules; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
  {
    code1: "0186",
    code2: "J06.9",
    type: "never_together",
    reason: "Psychiatric admission (0186) is for acute mental health conditions requiring inpatient care. J06.9 (URTI) is an acute respiratory infection — not a psychiatric admission diagnosis. F-code must be primary.",
    source: "CMS clinical edit guidelines; CCSA v11 discipline-diagnosis validation",
    category: "tariff_diagnosis_mismatch",
  },
];
