/**
 * CareOn mock data — realistic SA hospital patient records for demo/development.
 * Used by CareOnAdapter when DEMO_MODE=true or no API credentials configured.
 */

import type {
  UnifiedPatientRecord,
  HospitalEncounter,
  LabResult,
  Medication,
  VitalSign,
} from "../types";

// ── Mock Patients ──

export const MOCK_PATIENTS: Record<string, UnifiedPatientRecord> = {
  "MRN-001": {
    source: "careon",
    sourceId: "MRN-001",
    saIdNumber: "8501015800085",
    demographics: {
      firstName: "Sipho",
      lastName: "Mthembu",
      dateOfBirth: "1985-01-01",
      gender: "male",
      phone: "+27821234567",
      email: "sipho.mthembu@example.com",
      address: "42 Rivonia Road, Sandton, Gauteng, 2196",
      nextOfKin: "Nomsa Mthembu",
      nextOfKinPhone: "+27829876543",
    },
    allergies: [
      {
        substance: "Penicillin",
        reaction: "Anaphylaxis",
        severity: "life-threatening",
        recordedDate: "2019-03-15",
        source: "careon",
      },
      {
        substance: "Ibuprofen",
        reaction: "Urticaria",
        severity: "moderate",
        recordedDate: "2021-07-20",
        source: "careon",
      },
    ],
    medications: [],
    medicalAid: {
      schemeName: "Discovery Health",
      planName: "Classic Comprehensive",
      memberNumber: "DH-10284756",
      dependantCode: "00",
      status: "active",
    },
    lastSyncedAt: new Date().toISOString(),
  },
  "MRN-002": {
    source: "careon",
    sourceId: "MRN-002",
    saIdNumber: "9203125600083",
    demographics: {
      firstName: "Lerato",
      lastName: "Khumalo",
      dateOfBirth: "1992-03-12",
      gender: "female",
      phone: "+27731112233",
      email: "lerato.k@example.com",
      address: "15 Pretoria Street, Hatfield, Pretoria, 0028",
      nextOfKin: "Thabo Khumalo",
      nextOfKinPhone: "+27824445566",
    },
    allergies: [
      {
        substance: "Sulfonamides",
        reaction: "Rash",
        severity: "moderate",
        recordedDate: "2020-11-03",
        source: "careon",
      },
    ],
    medications: [],
    medicalAid: {
      schemeName: "Bonitas",
      planName: "BonComplete",
      memberNumber: "BON-5567823",
      dependantCode: "00",
      status: "active",
    },
    lastSyncedAt: new Date().toISOString(),
  },
  "MRN-003": {
    source: "careon",
    sourceId: "MRN-003",
    saIdNumber: "7806265800088",
    demographics: {
      firstName: "Pieter",
      lastName: "van der Merwe",
      dateOfBirth: "1978-06-26",
      gender: "male",
      phone: "+27609998877",
      email: "pieter.vdm@example.com",
      address: "88 Church Street, Stellenbosch, Western Cape, 7600",
    },
    allergies: [],
    medications: [],
    medicalAid: {
      schemeName: "Momentum Health",
      planName: "Summit",
      memberNumber: "MOM-9912345",
      dependantCode: "01",
      status: "active",
    },
    lastSyncedAt: new Date().toISOString(),
  },
  "MRN-004": {
    source: "careon",
    sourceId: "MRN-004",
    saIdNumber: "6510080200081",
    demographics: {
      firstName: "Fatima",
      lastName: "Jacobs",
      dateOfBirth: "1965-10-08",
      gender: "female",
      phone: "+27715554433",
      email: "fatima.j@example.com",
      address: "12 Kloof Street, Gardens, Cape Town, 8001",
      nextOfKin: "Ahmed Jacobs",
      nextOfKinPhone: "+27826667788",
    },
    allergies: [
      {
        substance: "Codeine",
        reaction: "Nausea and vomiting",
        severity: "moderate",
        recordedDate: "2017-09-10",
        source: "careon",
      },
      {
        substance: "Latex",
        reaction: "Contact dermatitis",
        severity: "mild",
        recordedDate: "2022-01-15",
        source: "careon",
      },
      {
        substance: "Metformin",
        reaction: "Lactic acidosis",
        severity: "severe",
        recordedDate: "2023-05-20",
        source: "careon",
      },
    ],
    medications: [],
    medicalAid: {
      schemeName: "GEMS",
      planName: "Emerald Value",
      memberNumber: "GEMS-7788990",
      dependantCode: "00",
      status: "active",
    },
    lastSyncedAt: new Date().toISOString(),
  },
};

// ── Mock Encounters ──

export const MOCK_ENCOUNTERS: Record<string, HospitalEncounter[]> = {
  "MRN-001": [
    {
      encounterId: "ENC-2026-001",
      patientId: "MRN-001",
      facility: "Netcare Milpark Hospital",
      facilityCode: "MILPARK",
      type: "inpatient",
      status: "discharged",
      admitDate: "2026-03-10T08:30:00Z",
      dischargeDate: "2026-03-14T11:00:00Z",
      ward: "Surgical Ward B",
      bed: "B-12",
      attendingDoctor: "Dr. R. Naidoo",
      referringDoctor: "Dr. S. Pillay",
      admitDiagnosis: "Acute appendicitis",
      dischargeDiagnoses: [
        { code: "K35.80", description: "Acute appendicitis, other and unspecified", type: "final", isPrimary: true },
        { code: "K65.0", description: "Generalised peritonitis", type: "comorbidity", isPrimary: false },
      ],
      procedures: [
        { code: "0DTJ4ZZ", description: "Laparoscopic appendectomy", date: "2026-03-10T14:00:00Z", performedBy: "Dr. R. Naidoo" },
      ],
      lengthOfStayDays: 4,
    },
    {
      encounterId: "ENC-2025-089",
      patientId: "MRN-001",
      facility: "Netcare Sunninghill Hospital",
      facilityCode: "SUNNINGHILL",
      type: "emergency",
      status: "discharged",
      admitDate: "2025-11-22T22:15:00Z",
      dischargeDate: "2025-11-23T06:00:00Z",
      ward: "Emergency Department",
      bed: "ED-3",
      attendingDoctor: "Dr. A. Moosa",
      referringDoctor: "",
      admitDiagnosis: "Chest pain, unspecified",
      dischargeDiagnoses: [
        { code: "R07.9", description: "Chest pain, unspecified", type: "final", isPrimary: true },
        { code: "I10", description: "Essential hypertension", type: "comorbidity", isPrimary: false },
      ],
      procedures: [],
      lengthOfStayDays: 0,
    },
  ],
  "MRN-002": [
    {
      encounterId: "ENC-2026-045",
      patientId: "MRN-002",
      facility: "Netcare Unitas Hospital",
      facilityCode: "UNITAS",
      type: "day_case",
      status: "discharged",
      admitDate: "2026-02-28T07:00:00Z",
      dischargeDate: "2026-02-28T16:30:00Z",
      ward: "Day Surgery Unit",
      bed: "DS-7",
      attendingDoctor: "Dr. M. Botha",
      referringDoctor: "Dr. L. Mahlangu",
      admitDiagnosis: "Bilateral tonsillitis, recurrent",
      dischargeDiagnoses: [
        { code: "J35.0", description: "Chronic tonsillitis", type: "final", isPrimary: true },
      ],
      procedures: [
        { code: "0CBP0ZZ", description: "Bilateral tonsillectomy", date: "2026-02-28T09:30:00Z", performedBy: "Dr. M. Botha" },
      ],
      lengthOfStayDays: 0,
    },
  ],
  "MRN-004": [
    {
      encounterId: "ENC-2026-078",
      patientId: "MRN-004",
      facility: "Netcare Christiaan Barnard Memorial Hospital",
      facilityCode: "CBMH",
      type: "inpatient",
      status: "admitted",
      admitDate: "2026-03-18T10:00:00Z",
      dischargeDate: null,
      ward: "Cardiology Ward",
      bed: "CW-5",
      attendingDoctor: "Dr. T. Pillay",
      referringDoctor: "Dr. F. Adams",
      admitDiagnosis: "Unstable angina",
      dischargeDiagnoses: [
        { code: "I20.0", description: "Unstable angina", type: "working", isPrimary: true },
        { code: "E11.9", description: "Type 2 diabetes mellitus without complications", type: "comorbidity", isPrimary: false },
        { code: "I10", description: "Essential hypertension", type: "comorbidity", isPrimary: false },
      ],
      procedures: [
        { code: "02703DZ", description: "Coronary angiography", date: "2026-03-18T14:30:00Z", performedBy: "Dr. T. Pillay" },
      ],
      lengthOfStayDays: null,
    },
    {
      encounterId: "ENC-2025-201",
      patientId: "MRN-004",
      facility: "Netcare Christiaan Barnard Memorial Hospital",
      facilityCode: "CBMH",
      type: "outpatient",
      status: "discharged",
      admitDate: "2025-09-15T09:00:00Z",
      dischargeDate: "2025-09-15T12:00:00Z",
      ward: "Cardiology Outpatient",
      bed: "",
      attendingDoctor: "Dr. T. Pillay",
      referringDoctor: "Dr. F. Adams",
      admitDiagnosis: "Follow-up: hypertension management",
      dischargeDiagnoses: [
        { code: "I10", description: "Essential hypertension", type: "final", isPrimary: true },
        { code: "E11.65", description: "Type 2 diabetes mellitus with hyperglycaemia", type: "comorbidity", isPrimary: false },
      ],
      procedures: [],
      lengthOfStayDays: 0,
    },
  ],
};

// ── Mock Lab Results ──

export const MOCK_LAB_RESULTS: Record<string, LabResult[]> = {
  "MRN-001": [
    {
      resultId: "LAB-2026-1001",
      patientId: "MRN-001",
      labReference: "LAN-GP-2026-88745",
      laboratory: "lancet",
      testCode: "FBC",
      testName: "Full Blood Count — White Cell Count",
      value: "14.2",
      unit: "x10^9/L",
      referenceRange: "4.0-11.0",
      abnormalFlag: "high",
      status: "final",
      collectedDate: "2026-03-10T09:00:00Z",
      reportedDate: "2026-03-10T15:30:00Z",
      orderingDoctor: "Dr. R. Naidoo",
    },
    {
      resultId: "LAB-2026-1002",
      patientId: "MRN-001",
      labReference: "LAN-GP-2026-88745",
      laboratory: "lancet",
      testCode: "CRP",
      testName: "C-Reactive Protein",
      value: "85.3",
      unit: "mg/L",
      referenceRange: "0-5",
      abnormalFlag: "critical_high",
      status: "final",
      collectedDate: "2026-03-10T09:00:00Z",
      reportedDate: "2026-03-10T15:30:00Z",
      orderingDoctor: "Dr. R. Naidoo",
    },
    {
      resultId: "LAB-2026-1003",
      patientId: "MRN-001",
      labReference: "LAN-GP-2026-88745",
      laboratory: "lancet",
      testCode: "CREAT",
      testName: "Creatinine",
      value: "88",
      unit: "umol/L",
      referenceRange: "64-104",
      abnormalFlag: "normal",
      status: "final",
      collectedDate: "2026-03-10T09:00:00Z",
      reportedDate: "2026-03-10T15:30:00Z",
      orderingDoctor: "Dr. R. Naidoo",
    },
  ],
  "MRN-004": [
    {
      resultId: "LAB-2026-2001",
      patientId: "MRN-004",
      labReference: "AMP-CT-2026-34521",
      laboratory: "ampath",
      testCode: "TROP-I",
      testName: "Troponin I (high-sensitivity)",
      value: "0.089",
      unit: "ng/mL",
      referenceRange: "0-0.04",
      abnormalFlag: "critical_high",
      status: "final",
      collectedDate: "2026-03-18T10:30:00Z",
      reportedDate: "2026-03-18T12:00:00Z",
      orderingDoctor: "Dr. T. Pillay",
    },
    {
      resultId: "LAB-2026-2002",
      patientId: "MRN-004",
      labReference: "AMP-CT-2026-34521",
      laboratory: "ampath",
      testCode: "HBA1C",
      testName: "Glycated Haemoglobin (HbA1c)",
      value: "8.2",
      unit: "%",
      referenceRange: "4.0-5.6",
      abnormalFlag: "high",
      status: "final",
      collectedDate: "2026-03-18T10:30:00Z",
      reportedDate: "2026-03-18T14:00:00Z",
      orderingDoctor: "Dr. T. Pillay",
    },
    {
      resultId: "LAB-2026-2003",
      patientId: "MRN-004",
      labReference: "AMP-CT-2026-34521",
      laboratory: "ampath",
      testCode: "LDL",
      testName: "LDL Cholesterol",
      value: "4.8",
      unit: "mmol/L",
      referenceRange: "0-3.0",
      abnormalFlag: "high",
      status: "final",
      collectedDate: "2026-03-18T10:30:00Z",
      reportedDate: "2026-03-18T14:00:00Z",
      orderingDoctor: "Dr. T. Pillay",
    },
    {
      resultId: "LAB-2026-2004",
      patientId: "MRN-004",
      labReference: "AMP-CT-2026-34521",
      laboratory: "ampath",
      testCode: "K",
      testName: "Potassium",
      value: "5.8",
      unit: "mmol/L",
      referenceRange: "3.5-5.1",
      abnormalFlag: "high",
      status: "final",
      collectedDate: "2026-03-18T10:30:00Z",
      reportedDate: "2026-03-18T14:00:00Z",
      orderingDoctor: "Dr. T. Pillay",
    },
  ],
};

// ── Mock Medications ──

export const MOCK_MEDICATIONS: Record<string, Medication[]> = {
  "MRN-001": [
    {
      name: "Augmentin 625mg",
      nappiCode: "708687001",
      dosage: "625mg",
      frequency: "Three times daily",
      route: "Oral",
      prescribedDate: "2026-03-10",
      prescribedBy: "Dr. R. Naidoo",
      safetyFlags: [],
      active: true,
    },
    {
      name: "Panado (Paracetamol) 500mg",
      nappiCode: "700403001",
      dosage: "1000mg",
      frequency: "Four times daily (max)",
      route: "Oral",
      prescribedDate: "2026-03-10",
      prescribedBy: "Dr. R. Naidoo",
      safetyFlags: [],
      active: true,
    },
    {
      name: "Amlodipine 5mg",
      nappiCode: "714259001",
      dosage: "5mg",
      frequency: "Once daily",
      route: "Oral",
      prescribedDate: "2025-06-15",
      prescribedBy: "Dr. S. Pillay",
      safetyFlags: [],
      active: true,
    },
  ],
  "MRN-004": [
    {
      name: "Aspirin 100mg",
      nappiCode: "700001001",
      dosage: "100mg",
      frequency: "Once daily",
      route: "Oral",
      prescribedDate: "2026-03-18",
      prescribedBy: "Dr. T. Pillay",
      safetyFlags: [],
      active: true,
    },
    {
      name: "Clopidogrel 75mg",
      nappiCode: "718392001",
      dosage: "75mg",
      frequency: "Once daily",
      route: "Oral",
      prescribedDate: "2026-03-18",
      prescribedBy: "Dr. T. Pillay",
      safetyFlags: [
        {
          type: "interaction",
          severity: "moderate",
          description: "Concurrent use with Aspirin increases bleeding risk. Monitor for signs of GI bleeding.",
          interactsWith: "Aspirin 100mg",
        },
      ],
      active: true,
    },
    {
      name: "Atorvastatin 40mg",
      nappiCode: "716723001",
      dosage: "40mg",
      frequency: "Once daily at bedtime",
      route: "Oral",
      prescribedDate: "2025-09-15",
      prescribedBy: "Dr. T. Pillay",
      safetyFlags: [],
      active: true,
    },
    {
      name: "Enoxaparin (Clexane) 60mg",
      nappiCode: "714501001",
      dosage: "60mg",
      frequency: "Twice daily",
      route: "Subcutaneous",
      prescribedDate: "2026-03-18",
      prescribedBy: "Dr. T. Pillay",
      safetyFlags: [
        {
          type: "interaction",
          severity: "high",
          description: "Triple antithrombotic therapy (Aspirin + Clopidogrel + Enoxaparin). High bleeding risk — ensure PPI cover and monitor platelets.",
          interactsWith: "Aspirin 100mg, Clopidogrel 75mg",
        },
      ],
      active: true,
    },
    {
      name: "Glucophage (Metformin) 850mg",
      nappiCode: "710855001",
      dosage: "850mg",
      frequency: "Twice daily with meals",
      route: "Oral",
      prescribedDate: "2023-04-10",
      prescribedBy: "Dr. F. Adams",
      safetyFlags: [
        {
          type: "contraindication",
          severity: "high",
          description: "Patient has documented allergy/intolerance to Metformin (lactic acidosis). Review alternative hypoglycaemic agent.",
        },
      ],
      active: false,
    },
    {
      name: "Perindopril 4mg",
      nappiCode: "715890001",
      dosage: "4mg",
      frequency: "Once daily",
      route: "Oral",
      prescribedDate: "2024-01-20",
      prescribedBy: "Dr. F. Adams",
      safetyFlags: [
        {
          type: "dose_check",
          severity: "moderate",
          description: "Monitor potassium levels — current K+ is 5.8 mmol/L (elevated). Consider dose reduction or switch to ARB.",
        },
      ],
      active: true,
    },
  ],
};

// ── Mock Vitals ──

export const MOCK_VITALS: Record<string, VitalSign[]> = {
  "MRN-001": [
    {
      patientId: "MRN-001",
      deviceId: "PHIL-CAP-MILPARK-B12",
      timestamp: "2026-03-13T08:00:00Z",
      heartRate: 78,
      systolicBP: 128,
      diastolicBP: 82,
      temperature: 36.8,
      respiratoryRate: 16,
      oxygenSaturation: 97,
      painScore: 2,
      gcsScore: 15,
      source: "philips_capsule",
    },
    {
      patientId: "MRN-001",
      deviceId: "PHIL-CAP-MILPARK-B12",
      timestamp: "2026-03-12T20:00:00Z",
      heartRate: 82,
      systolicBP: 132,
      diastolicBP: 85,
      temperature: 37.2,
      respiratoryRate: 18,
      oxygenSaturation: 96,
      painScore: 4,
      gcsScore: 15,
      source: "philips_capsule",
    },
  ],
  "MRN-004": [
    {
      patientId: "MRN-004",
      deviceId: "PHIL-CAP-CBMH-CW5",
      timestamp: "2026-03-19T06:00:00Z",
      heartRate: 92,
      systolicBP: 158,
      diastolicBP: 95,
      temperature: 36.9,
      respiratoryRate: 20,
      oxygenSaturation: 94,
      painScore: 5,
      gcsScore: 15,
      source: "philips_capsule",
    },
    {
      patientId: "MRN-004",
      deviceId: "PHIL-CAP-CBMH-CW5",
      timestamp: "2026-03-18T22:00:00Z",
      heartRate: 98,
      systolicBP: 165,
      diastolicBP: 100,
      temperature: 37.0,
      respiratoryRate: 22,
      oxygenSaturation: 93,
      painScore: 7,
      gcsScore: 15,
      source: "philips_capsule",
    },
    {
      patientId: "MRN-004",
      deviceId: "PHIL-CAP-CBMH-CW5",
      timestamp: "2026-03-18T14:00:00Z",
      heartRate: 105,
      systolicBP: 172,
      diastolicBP: 105,
      temperature: 36.8,
      respiratoryRate: 24,
      oxygenSaturation: 92,
      painScore: 8,
      gcsScore: 15,
      source: "philips_capsule",
    },
  ],
};
