// AI Training Data Generator — Claims Rejection Predictor
// Generates annotated training examples for the AI rejection predictor.
// 100 examples across all 7 schemes covering valid claims, specificity errors,
// missing external causes, gender mismatches, PMB opportunities, CDL opportunities,
// and tariff unbundling violations.

import type { ClaimLineItem, ValidationSeverity } from "./types";

// ─── TYPES ──────────────────────────────────────────────────────

export type TrainingOutcome =
  | "accepted"
  | "rejected_specificity"
  | "rejected_missing_ecc"
  | "rejected_gender_mismatch"
  | "rejected_pmb_missed"
  | "rejected_cdl_missed"
  | "rejected_unbundling"
  | "rejected_no_preauth"
  | "rejected_late_submission"
  | "rejected_duplicate"
  | "rejected_benefit_exhausted"
  | "rejected_network_violation"
  | "warning_suboptimal_coding";

export interface TrainingExample {
  id: number;
  claim: ClaimLineItem;
  schemeCode: string;
  expectedOutcome: TrainingOutcome;
  reason: string;
  fix: string;
  severity: ValidationSeverity;
  category: string;
  /** Estimated probability of rejection (0-1) */
  rejectionProbability: number;
}

export interface TrainingDataset {
  version: string;
  generatedAt: string;
  totalExamples: number;
  outcomeDistribution: Record<string, number>;
  examples: TrainingExample[];
}

// ─── TRAINING EXAMPLES ──────────────────────────────────────────

const TRAINING_EXAMPLES: TrainingExample[] = [
  // ═══════════════════════════════════════════════════════════════
  // VALID CLAIMS (30 examples — correctly coded, should be accepted)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 1,
    claim: { lineNumber: 1, primaryICD10: "J06.9", tariffCode: "0190", patientGender: "F", patientAge: 34, amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid GP consultation for upper respiratory infection. Code has 4-character specificity. Amount within Discovery tariff.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 2,
    claim: { lineNumber: 1, primaryICD10: "I10.0", tariffCode: "0190", patientGender: "M", patientAge: 55, amount: 430, dateOfService: "2026-03-10" },
    schemeCode: "GEMS",
    expectedOutcome: "accepted",
    reason: "Valid GP consultation for essential hypertension. 4th character specificity meets GEMS strict requirements.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 3,
    claim: { lineNumber: 1, primaryICD10: "E11.2", tariffCode: "0190", patientGender: "F", patientAge: 62, amount: 470, nappiCode: "714627001", dateOfService: "2026-03-12" },
    schemeCode: "BON",
    expectedOutcome: "accepted",
    reason: "Valid consultation for Type 2 diabetes with renal complications. Specific diagnosis code. NAPPI for metformin included.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 4,
    claim: { lineNumber: 1, primaryICD10: "S52.50", secondaryICD10: ["W19.9"], tariffCode: "0196", patientGender: "M", patientAge: 28, amount: 850, dateOfService: "2026-03-14" },
    schemeCode: "MS",
    expectedOutcome: "accepted",
    reason: "Valid fracture treatment with external cause code. S52.50 (distal radius fracture) paired with W19.9 (unspecified fall). Meets Medshield ECC requirements.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 5,
    claim: { lineNumber: 1, primaryICD10: "J45.1", tariffCode: "0190", patientGender: "F", patientAge: 8, amount: 480, dateOfService: "2026-03-11" },
    schemeCode: "MH",
    expectedOutcome: "accepted",
    reason: "Valid consultation for non-allergic asthma (PMB condition). Specific code. Child patient — age appropriate.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 6,
    claim: { lineNumber: 1, primaryICD10: "K21.0", tariffCode: "0190", patientGender: "M", patientAge: 45, amount: 500, dateOfService: "2026-03-13" },
    schemeCode: "BM",
    expectedOutcome: "accepted",
    reason: "Valid consultation for GORD (gastro-oesophageal reflux with oesophagitis). Specific 4th character. Bestmed moderate requirements met.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.03,
  },
  {
    id: 7,
    claim: { lineNumber: 1, primaryICD10: "N18.3", tariffCode: "0190", patientGender: "F", patientAge: 70, amount: 520, dateOfService: "2026-03-09" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid consultation for CKD stage 3 (CDL condition). Fully specified. CDL and PMB benefits applicable.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 8,
    claim: { lineNumber: 1, primaryICD10: "B20.0", tariffCode: "0190", patientGender: "M", patientAge: 38, amount: 520, nappiCode: "828602001", dateOfService: "2026-03-08" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid HIV consultation with ARV medication (PMB condition). Correctly coded B20.0 with NAPPI for ARV.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 9,
    claim: { lineNumber: 1, primaryICD10: "H25.1", tariffCode: "0190", patientGender: "F", patientAge: 72, amount: 430, dateOfService: "2026-03-07" },
    schemeCode: "GEMS",
    expectedOutcome: "accepted",
    reason: "Valid consultation for nuclear cataract. Specific code. Pre-auth not yet needed (consultation only, not surgery).",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 10,
    claim: { lineNumber: 1, primaryICD10: "O80.0", tariffCode: "0190", patientGender: "F", patientAge: 29, amount: 470, dateOfService: "2026-03-06" },
    schemeCode: "BON",
    expectedOutcome: "accepted",
    reason: "Valid antenatal consultation (PMB). Obstetric code for normal delivery. Gender appropriate.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 11,
    claim: { lineNumber: 1, primaryICD10: "M54.5", tariffCode: "0190", patientGender: "M", patientAge: 50, amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid consultation for low back pain. 4th character specificity. Discovery managed care info flag but not rejection.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.08,
  },
  {
    id: 12,
    claim: { lineNumber: 1, primaryICD10: "L20.9", tariffCode: "0190", patientGender: "F", patientAge: 3, amount: 480, dateOfService: "2026-03-14" },
    schemeCode: "MH",
    expectedOutcome: "accepted",
    reason: "Valid paediatric consultation for atopic dermatitis (eczema). Age appropriate. Specific code.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 13,
    claim: { lineNumber: 1, primaryICD10: "G40.3", tariffCode: "0190", patientGender: "M", patientAge: 22, amount: 500, nappiCode: "745891001", dateOfService: "2026-03-13" },
    schemeCode: "BM",
    expectedOutcome: "accepted",
    reason: "Valid consultation for generalised epilepsy (CDL condition). NAPPI for valproate. Bestmed CDL benefits apply.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.03,
  },
  {
    id: 14,
    claim: { lineNumber: 1, primaryICD10: "R10.4", tariffCode: "0190", patientGender: "F", patientAge: 42, amount: 460, dateOfService: "2026-03-12" },
    schemeCode: "MS",
    expectedOutcome: "accepted",
    reason: "Valid consultation for unspecified abdominal pain. R-codes (symptoms) are valid when diagnosis is not yet confirmed.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 15,
    claim: { lineNumber: 1, primaryICD10: "T78.4", secondaryICD10: ["X58.9"], tariffCode: "0190", patientGender: "M", patientAge: 12, amount: 520, dateOfService: "2026-03-11" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid allergic reaction with external cause code. T78.4 (allergy, unspecified) with X58.9 (exposure to other specified factors). Correctly paired.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 16,
    claim: { lineNumber: 1, primaryICD10: "Z00.0", tariffCode: "0190", patientGender: "F", patientAge: 40, amount: 430, dateOfService: "2026-03-10" },
    schemeCode: "GEMS",
    expectedOutcome: "accepted",
    reason: "Valid general medical examination. Z00.0 (general exam, no complaint). Routine screening covered on all GEMS options.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 17,
    claim: { lineNumber: 1, primaryICD10: "E03.9", tariffCode: "0190", patientGender: "F", patientAge: 55, amount: 470, nappiCode: "706712001", dateOfService: "2026-03-09" },
    schemeCode: "BON",
    expectedOutcome: "accepted",
    reason: "Valid consultation for hypothyroidism (CDL condition). NAPPI for levothyroxine. CDL benefits applicable.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 18,
    claim: { lineNumber: 1, primaryICD10: "J18.9", tariffCode: "0190", patientGender: "M", patientAge: 67, amount: 500, dateOfService: "2026-03-08" },
    schemeCode: "BM",
    expectedOutcome: "accepted",
    reason: "Valid consultation for pneumonia (PMB condition as emergency). J18.9 is acceptable as unspecified pneumonia for initial visit.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 19,
    claim: { lineNumber: 1, primaryICD10: "F32.1", tariffCode: "0190", patientGender: "F", patientAge: 35, amount: 480, dateOfService: "2026-03-07" },
    schemeCode: "MH",
    expectedOutcome: "accepted",
    reason: "Valid consultation for moderate depressive episode (CDL condition). F32.1 is specific. Mental health benefits apply.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 20,
    claim: { lineNumber: 1, primaryICD10: "K50.0", tariffCode: "0190", patientGender: "M", patientAge: 30, amount: 520, dateOfService: "2026-03-06" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid consultation for Crohn's disease of small intestine (CDL condition). K50.0 is fully specific. CDL and PMB benefits apply.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 21,
    claim: { lineNumber: 1, primaryICD10: "N39.0", tariffCode: "0190", patientGender: "F", patientAge: 26, amount: 430, dateOfService: "2026-03-15" },
    schemeCode: "GEMS",
    expectedOutcome: "accepted",
    reason: "Valid consultation for urinary tract infection. N39.0 is specific. Gender and age appropriate. Within GEMS tariff.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 22,
    claim: { lineNumber: 1, primaryICD10: "M79.3", tariffCode: "0190", patientGender: "M", patientAge: 48, amount: 460, dateOfService: "2026-03-14" },
    schemeCode: "MS",
    expectedOutcome: "accepted",
    reason: "Valid consultation for panniculitis. M79.3 is specific. Age and gender appropriate.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 23,
    claim: { lineNumber: 1, primaryICD10: "A09.0", tariffCode: "0190", patientGender: "F", patientAge: 5, amount: 480, dateOfService: "2026-03-13" },
    schemeCode: "MH",
    expectedOutcome: "accepted",
    reason: "Valid paediatric consultation for gastroenteritis. A09.0 is specific. Age appropriate.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 24,
    claim: { lineNumber: 1, primaryICD10: "H10.1", tariffCode: "0190", patientGender: "M", patientAge: 33, amount: 500, dateOfService: "2026-03-12" },
    schemeCode: "BM",
    expectedOutcome: "accepted",
    reason: "Valid consultation for acute atopic conjunctivitis. H10.1 is specific. Bestmed moderate requirements met.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.03,
  },
  {
    id: 25,
    claim: { lineNumber: 1, primaryICD10: "I21.0", tariffCode: "0190", patientGender: "M", patientAge: 58, amount: 520, dateOfService: "2026-03-11" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid emergency consultation for acute anterior STEMI (PMB emergency). I21.0 is specific and PMB-protected.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.02,
  },
  {
    id: 26,
    claim: { lineNumber: 1, primaryICD10: "G35.0", tariffCode: "0190", patientGender: "F", patientAge: 41, amount: 430, dateOfService: "2026-03-10" },
    schemeCode: "GEMS",
    expectedOutcome: "accepted",
    reason: "Valid consultation for multiple sclerosis (CDL condition). G35.0 specific. CDL benefits apply.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 27,
    claim: { lineNumber: 1, primaryICD10: "L50.0", tariffCode: "0190", patientGender: "F", patientAge: 18, amount: 470, dateOfService: "2026-03-09" },
    schemeCode: "BON",
    expectedOutcome: "accepted",
    reason: "Valid consultation for allergic urticaria. L50.0 is specific. Gender and age appropriate.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 28,
    claim: { lineNumber: 1, primaryICD10: "D50.0", tariffCode: "0190", patientGender: "F", patientAge: 32, amount: 460, dateOfService: "2026-03-08" },
    schemeCode: "MS",
    expectedOutcome: "accepted",
    reason: "Valid consultation for iron deficiency anaemia secondary to blood loss. D50.0 is specific.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },
  {
    id: 29,
    claim: { lineNumber: 1, primaryICD10: "M81.0", tariffCode: "0190", patientGender: "F", patientAge: 65, amount: 500, dateOfService: "2026-03-07" },
    schemeCode: "BM",
    expectedOutcome: "accepted",
    reason: "Valid consultation for postmenopausal osteoporosis (CDL condition). M81.0 specific. Age and gender appropriate.",
    fix: "No fix needed — correctly coded.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.03,
  },
  {
    id: 30,
    claim: { lineNumber: 1, primaryICD10: "C50.9", tariffCode: "0190", patientGender: "F", patientAge: 52, amount: 520, dateOfService: "2026-03-06" },
    schemeCode: "DH",
    expectedOutcome: "accepted",
    reason: "Valid oncology consultation for breast cancer (PMB). C50.9 is valid initial code pending staging. Discovery oncology programme registration needed for treatment.",
    fix: "No fix needed — correctly coded for initial consultation.",
    severity: "info",
    category: "valid",
    rejectionProbability: 0.05,
  },

  // ═══════════════════════════════════════════════════════════════
  // SPECIFICITY ERRORS (15 examples)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 31,
    claim: { lineNumber: 1, primaryICD10: "I10", tariffCode: "0190", patientGender: "M", patientAge: 55, amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_specificity",
    reason: "I10 is a 3-character code. Discovery requires 4th character. I10.0 (essential) or I10.9 (unspecified) needed.",
    fix: "Change I10 to I10.0 (essential/primary hypertension) or I10.9 if unspecified.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.92,
  },
  {
    id: 32,
    claim: { lineNumber: 1, primaryICD10: "J45", tariffCode: "0190", patientGender: "F", patientAge: 12, amount: 430, dateOfService: "2026-03-14" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_specificity",
    reason: "J45 is a 3-character code. GEMS strict specificity rejects without 4th character. J45.0 (allergic), J45.1 (non-allergic), J45.9 (unspecified) required.",
    fix: "Change J45 to J45.0, J45.1, J45.8, or J45.9 based on clinical presentation.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.95,
  },
  {
    id: 33,
    claim: { lineNumber: 1, primaryICD10: "E11", tariffCode: "0190", patientGender: "M", patientAge: 60, amount: 470, dateOfService: "2026-03-13" },
    schemeCode: "MH",
    expectedOutcome: "rejected_specificity",
    reason: "E11 lacks 4th character. Momentum strict enforcement requires E11.0-E11.9 to specify complications.",
    fix: "Change E11 to E11.9 (without complications) or E11.2/E11.3/E11.4 if complications exist.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.90,
  },
  {
    id: 34,
    claim: { lineNumber: 1, primaryICD10: "M54", tariffCode: "0190", patientGender: "F", patientAge: 48, amount: 460, dateOfService: "2026-03-12" },
    schemeCode: "DH",
    expectedOutcome: "rejected_specificity",
    reason: "M54 is 3-character. Discovery strict: needs M54.5 (low back pain), M54.4 (lumbago with sciatica), M54.2 (cervicalgia), etc.",
    fix: "Specify the anatomical region: M54.5 (lumbar), M54.2 (cervical), M54.4 (with sciatica).",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.92,
  },
  {
    id: 35,
    claim: { lineNumber: 1, primaryICD10: "K29", tariffCode: "0190", patientGender: "M", patientAge: 38, amount: 430, dateOfService: "2026-03-11" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_specificity",
    reason: "K29 lacks specificity. Must specify K29.0 (acute haemorrhagic), K29.3 (superficial chronic), K29.7 (unspecified).",
    fix: "Change K29 to K29.7 (unspecified) at minimum, or more specific subtype.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.93,
  },
  {
    id: 36,
    claim: { lineNumber: 1, primaryICD10: "N40", tariffCode: "0190", patientGender: "M", patientAge: 68, amount: 520, dateOfService: "2026-03-10" },
    schemeCode: "DH",
    expectedOutcome: "rejected_specificity",
    reason: "N40 (BPH) is 3-character. Discovery requires N40.0 (with lower urinary tract symptoms) or N40.1 (without LUTS).",
    fix: "Change to N40.0 or N40.1 based on presence of LUTS.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.90,
  },
  {
    id: 37,
    claim: { lineNumber: 1, primaryICD10: "G43", tariffCode: "0190", patientGender: "F", patientAge: 30, amount: 480, dateOfService: "2026-03-09" },
    schemeCode: "MH",
    expectedOutcome: "rejected_specificity",
    reason: "G43 lacks 4th character. Momentum strict: G43.0 (with aura), G43.1 (without aura), G43.9 (unspecified) required.",
    fix: "Change G43 to G43.0, G43.1, or G43.9 based on migraine type.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.90,
  },
  {
    id: 38,
    claim: { lineNumber: 1, primaryICD10: "L40", tariffCode: "0190", patientGender: "M", patientAge: 45, amount: 470, dateOfService: "2026-03-08" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_specificity",
    reason: "L40 lacks 4th character for CDL condition. Must specify L40.0 (vulgaris), L40.5 (with arthropathy), etc.",
    fix: "Change to L40.0 (plaque psoriasis) or L40.5 (psoriatic arthropathy) for CDL registration.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.93,
  },
  {
    id: 39,
    claim: { lineNumber: 1, primaryICD10: "F32", tariffCode: "0190", patientGender: "F", patientAge: 40, amount: 520, dateOfService: "2026-03-07" },
    schemeCode: "DH",
    expectedOutcome: "rejected_specificity",
    reason: "F32 needs severity specifier. F32.0 (mild), F32.1 (moderate), F32.2 (severe without psychosis), F32.3 (severe with psychosis).",
    fix: "Change to F32.0, F32.1, F32.2, or F32.3 based on assessed severity.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.92,
  },
  {
    id: 40,
    claim: { lineNumber: 1, primaryICD10: "M06", tariffCode: "0190", patientGender: "F", patientAge: 55, amount: 430, dateOfService: "2026-03-06" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_specificity",
    reason: "M06 (other rheumatoid arthritis) lacks 4th character. M06.0 (seronegative RA), M06.9 (unspecified) needed.",
    fix: "Change to M06.0 or M06.9 based on serological status.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.93,
  },
  {
    id: 41,
    claim: { lineNumber: 1, primaryICD10: "H25", tariffCode: "0190", patientGender: "M", patientAge: 75, amount: 460, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_specificity",
    reason: "H25 (senile cataract) needs type: H25.0 (incipient), H25.1 (nuclear), H25.2 (morgagnian), H25.9 (unspecified).",
    fix: "Change to H25.1 (nuclear — most common) or H25.9 (unspecified) at minimum.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.90,
  },
  {
    id: 42,
    claim: { lineNumber: 1, primaryICD10: "J44", tariffCode: "0190", patientGender: "M", patientAge: 65, amount: 480, dateOfService: "2026-03-14" },
    schemeCode: "MH",
    expectedOutcome: "rejected_specificity",
    reason: "J44 (COPD) needs 4th character. J44.0 (acute exacerbation), J44.1 (with acute lower resp infection), J44.9 (unspecified).",
    fix: "Change to J44.0, J44.1, or J44.9 based on presentation.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.90,
  },
  {
    id: 43,
    claim: { lineNumber: 1, primaryICD10: "K51", tariffCode: "0190", patientGender: "F", patientAge: 33, amount: 520, dateOfService: "2026-03-13" },
    schemeCode: "DH",
    expectedOutcome: "rejected_specificity",
    reason: "K51 (ulcerative colitis — CDL condition) needs 4th character. K51.0 (enterocolitis), K51.9 (unspecified) required.",
    fix: "Change to K51.0 (pancolitis) or K51.9 (unspecified) at minimum.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.92,
  },
  {
    id: 44,
    claim: { lineNumber: 1, primaryICD10: "N18", tariffCode: "0190", patientGender: "M", patientAge: 72, amount: 430, dateOfService: "2026-03-12" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_specificity",
    reason: "N18 (CKD — CDL condition) needs stage: N18.1 (stage 1), N18.3 (stage 3), N18.5 (stage 5/ESRD).",
    fix: "Specify CKD stage: N18.1-N18.5 or N18.9 (unspecified stage).",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.95,
  },
  {
    id: 45,
    claim: { lineNumber: 1, primaryICD10: "I50", tariffCode: "0190", patientGender: "M", patientAge: 60, amount: 500, dateOfService: "2026-03-11" },
    schemeCode: "MH",
    expectedOutcome: "rejected_specificity",
    reason: "I50 (heart failure — CDL condition) needs 4th character. I50.0 (congestive), I50.1 (left ventricular), I50.9 (unspecified).",
    fix: "Change to I50.0 (congestive HF — most common), I50.1, or I50.9.",
    severity: "error",
    category: "specificity",
    rejectionProbability: 0.90,
  },

  // ═══════════════════════════════════════════════════════════════
  // MISSING EXTERNAL CAUSE CODES (10 examples)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 46,
    claim: { lineNumber: 1, primaryICD10: "S52.50", tariffCode: "0196", patientGender: "M", patientAge: 35, amount: 850, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S52.50 (distal radius fracture) is an injury code requiring an external cause code (V/W/X/Y). No secondary ECC provided.",
    fix: "Add external cause code: W19.9 (fall), V89.9 (MVA), W22.9 (struck by object), etc.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.88,
  },
  {
    id: 47,
    claim: { lineNumber: 1, primaryICD10: "S82.10", tariffCode: "0196", patientGender: "F", patientAge: 28, amount: 1200, dateOfService: "2026-03-14" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S82.10 (tibial fracture) requires external cause. GEMS strict ECC enforcement.",
    fix: "Add W19.9 (fall), V03.1 (pedestrian injury), or appropriate external cause code.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.92,
  },
  {
    id: 48,
    claim: { lineNumber: 1, primaryICD10: "T14.0", tariffCode: "0190", patientGender: "M", patientAge: 22, amount: 520, dateOfService: "2026-03-13" },
    schemeCode: "MS",
    expectedOutcome: "rejected_missing_ecc",
    reason: "T14.0 (superficial injury, unspecified) requires external cause. Medshield is particularly strict on ECC.",
    fix: "Add W19.9 (fall), W22.9 (struck), W26.9 (cut by sharp object), or appropriate cause.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.94,
  },
  {
    id: 49,
    claim: { lineNumber: 1, primaryICD10: "S06.0", tariffCode: "0190", patientGender: "F", patientAge: 45, amount: 520, dateOfService: "2026-03-12" },
    schemeCode: "DH",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S06.0 (concussion) is a head injury requiring external cause. Critical for RAF claim determination.",
    fix: "Add V89.9 (MVA), W19.9 (fall), W22.9 (struck), or appropriate cause. If MVA, may be RAF claim.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.90,
  },
  {
    id: 50,
    claim: { lineNumber: 1, primaryICD10: "S93.40", tariffCode: "0190", patientGender: "M", patientAge: 19, amount: 460, dateOfService: "2026-03-11" },
    schemeCode: "BON",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S93.40 (ankle sprain) requires external cause. Common sports injury — use W19 or W21.",
    fix: "Add W19.9 (fall during sport), W21.0 (struck by ball), or other sports cause code.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.85,
  },
  {
    id: 51,
    claim: { lineNumber: 1, primaryICD10: "S42.00", tariffCode: "0196", patientGender: "F", patientAge: 70, amount: 950, dateOfService: "2026-03-10" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S42.00 (clavicle fracture) requires external cause. Elderly patient — likely fall.",
    fix: "Add W19.9 (unspecified fall) or W01.0 (fall on same level from slipping).",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.92,
  },
  {
    id: 52,
    claim: { lineNumber: 1, primaryICD10: "T30.0", tariffCode: "0196", patientGender: "M", patientAge: 8, amount: 750, dateOfService: "2026-03-09" },
    schemeCode: "MS",
    expectedOutcome: "rejected_missing_ecc",
    reason: "T30.0 (burn, unspecified) requires external cause. Child — must determine mechanism for reporting.",
    fix: "Add X19.9 (exposure to unspecified heat/fire), X12.9 (contact with hot liquids), or appropriate cause.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.94,
  },
  {
    id: 53,
    claim: { lineNumber: 1, primaryICD10: "S61.0", tariffCode: "0196", patientGender: "M", patientAge: 42, amount: 680, dateOfService: "2026-03-08" },
    schemeCode: "MH",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S61.0 (open wound of finger) requires external cause. Workplace injury? Determine if COIDA or medical aid claim.",
    fix: "Add W26.9 (cut by sharp object), W45.9 (foreign body), or W31.9 (machinery). If workplace, may be COIDA claim.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.88,
  },
  {
    id: 54,
    claim: { lineNumber: 1, primaryICD10: "S72.00", tariffCode: "0196", patientGender: "F", patientAge: 78, amount: 1500, dateOfService: "2026-03-07" },
    schemeCode: "DH",
    expectedOutcome: "rejected_missing_ecc",
    reason: "S72.00 (neck of femur fracture) requires external cause. Elderly female — critical for osteoporotic fracture tracking.",
    fix: "Add W19.9 (fall) or W01.0 (fall from slipping). Consider adding M81.0 as secondary (osteoporosis).",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.90,
  },
  {
    id: 55,
    claim: { lineNumber: 1, primaryICD10: "T78.2", tariffCode: "0190", patientGender: "M", patientAge: 25, amount: 520, dateOfService: "2026-03-06" },
    schemeCode: "BM",
    expectedOutcome: "rejected_missing_ecc",
    reason: "T78.2 (anaphylactic shock) requires external cause code to identify allergen exposure.",
    fix: "Add X58.9 (exposure to other specified factors) or T63 (toxic effects of animal venom) if relevant.",
    severity: "error",
    category: "missing_ecc",
    rejectionProbability: 0.82,
  },

  // ═══════════════════════════════════════════════════════════════
  // GENDER MISMATCHES (10 examples)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 56,
    claim: { lineNumber: 1, primaryICD10: "N40.0", tariffCode: "0190", patientGender: "F", patientAge: 65, amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "N40.0 (benign prostatic hyperplasia) is male-only. Patient gender on file is Female.",
    fix: "Verify patient gender. If female, the diagnosis is incorrect. If male, correct the gender field.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.98,
  },
  {
    id: 57,
    claim: { lineNumber: 1, primaryICD10: "C61", tariffCode: "0190", patientGender: "F", patientAge: 70, amount: 430, dateOfService: "2026-03-14" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "C61 (prostate cancer) is male-only. Patient recorded as Female.",
    fix: "Correct the patient gender to Male, or review the diagnosis if the patient is female.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.99,
  },
  {
    id: 58,
    claim: { lineNumber: 1, primaryICD10: "N80.0", tariffCode: "0190", patientGender: "M", patientAge: 35, amount: 470, dateOfService: "2026-03-13" },
    schemeCode: "BON",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "N80.0 (endometriosis of uterus) is female-only. Patient recorded as Male.",
    fix: "Correct patient gender to Female, or review the diagnosis.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.98,
  },
  {
    id: 59,
    claim: { lineNumber: 1, primaryICD10: "C56", tariffCode: "0190", patientGender: "M", patientAge: 55, amount: 500, dateOfService: "2026-03-12" },
    schemeCode: "MH",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "C56 (ovarian cancer) is female-only. Patient recorded as Male.",
    fix: "Correct patient gender to Female, or review diagnosis code.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.99,
  },
  {
    id: 60,
    claim: { lineNumber: 1, primaryICD10: "O80.0", tariffCode: "0190", patientGender: "M", patientAge: 28, amount: 460, dateOfService: "2026-03-11" },
    schemeCode: "MS",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "O80.0 (single spontaneous delivery) is female-only. Patient recorded as Male.",
    fix: "Correct patient gender to Female. Obstetric codes are always female.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.99,
  },
  {
    id: 61,
    claim: { lineNumber: 1, primaryICD10: "D25.9", tariffCode: "0190", patientGender: "M", patientAge: 42, amount: 520, dateOfService: "2026-03-10" },
    schemeCode: "DH",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "D25.9 (uterine leiomyoma) is female-only. Patient recorded as Male.",
    fix: "Correct patient gender to Female, or review the diagnosis.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.98,
  },
  {
    id: 62,
    claim: { lineNumber: 1, primaryICD10: "N41.0", tariffCode: "0190", patientGender: "F", patientAge: 50, amount: 430, dateOfService: "2026-03-09" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "N41.0 (acute prostatitis) is male-only. Patient recorded as Female.",
    fix: "Correct patient gender to Male, or review the diagnosis.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.98,
  },
  {
    id: 63,
    claim: { lineNumber: 1, primaryICD10: "C53.9", tariffCode: "0190", patientGender: "M", patientAge: 38, amount: 480, dateOfService: "2026-03-08" },
    schemeCode: "MH",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "C53.9 (cervical cancer) is female-only. Patient recorded as Male.",
    fix: "Correct patient gender to Female, or review diagnosis code.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.99,
  },
  {
    id: 64,
    claim: { lineNumber: 1, primaryICD10: "N83.2", tariffCode: "0190", patientGender: "M", patientAge: 30, amount: 500, dateOfService: "2026-03-07" },
    schemeCode: "BM",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "N83.2 (other ovarian cysts) is female-only. Patient recorded as Male.",
    fix: "Correct patient gender to Female, or review diagnosis.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.98,
  },
  {
    id: 65,
    claim: { lineNumber: 1, primaryICD10: "E29.1", tariffCode: "0190", patientGender: "F", patientAge: 45, amount: 470, dateOfService: "2026-03-06" },
    schemeCode: "BON",
    expectedOutcome: "rejected_gender_mismatch",
    reason: "E29.1 (testicular hypofunction) is male-only. Patient recorded as Female.",
    fix: "Correct patient gender to Male, or review diagnosis code.",
    severity: "error",
    category: "gender_mismatch",
    rejectionProbability: 0.98,
  },

  // ═══════════════════════════════════════════════════════════════
  // PMB OPPORTUNITIES MISSED (10 examples)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 66,
    claim: { lineNumber: 1, primaryICD10: "I25.9", tariffCode: "0190", patientGender: "M", patientAge: 58, amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_pmb_missed",
    reason: "Patient had acute MI but coded as I25.9 (chronic IHD). I21.x is a PMB emergency — guaranteed payment. I25.9 hits benefit limits.",
    fix: "If acute event, change to I21.0/I21.1/I21.9. PMB protection ensures payment regardless of benefit status.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.15,
  },
  {
    id: 67,
    claim: { lineNumber: 1, primaryICD10: "J20.9", tariffCode: "0190", patientGender: "F", patientAge: 8, amount: 430, dateOfService: "2026-03-14" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_pmb_missed",
    reason: "Child with chronic asthma coded as J20.9 (acute bronchitis). If underlying asthma exists, J45.x is PMB and CDL — much better coverage.",
    fix: "If patient has diagnosed asthma, change primary to J45.0/J45.9 with J20.9 as secondary (acute exacerbation).",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 68,
    claim: { lineNumber: 1, primaryICD10: "R73.0", tariffCode: "0190", patientGender: "M", patientAge: 55, amount: 470, dateOfService: "2026-03-13" },
    schemeCode: "BON",
    expectedOutcome: "rejected_pmb_missed",
    reason: "R73.0 (abnormal glucose tolerance) used for confirmed diabetic. E11.x is PMB and CDL — chronic benefits and guaranteed payment.",
    fix: "If diabetes is confirmed, change to E11.9 (Type 2 without complications) or E11.x with complication codes. Register for CDL.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 69,
    claim: { lineNumber: 1, primaryICD10: "G47.3", tariffCode: "0190", patientGender: "M", patientAge: 42, amount: 520, dateOfService: "2026-03-12" },
    schemeCode: "DH",
    expectedOutcome: "rejected_pmb_missed",
    reason: "G47.3 (sleep apnoea) when patient also has epilepsy. G40.x is PMB/CDL — should be primary if seizures are the main condition.",
    fix: "If epilepsy is the primary condition, use G40.x as primary (PMB/CDL). G47.3 can remain as secondary.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 70,
    claim: { lineNumber: 1, primaryICD10: "I67.9", tariffCode: "0190", patientGender: "F", patientAge: 72, amount: 430, dateOfService: "2026-03-11" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_pmb_missed",
    reason: "I67.9 (cerebrovascular disease) used for patient who had a stroke. I63.x (cerebral infarction) is PMB emergency — guaranteed payment.",
    fix: "If stroke occurred, change to I63.0-I63.9 (cerebral infarction) for PMB emergency protection.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 71,
    claim: { lineNumber: 1, primaryICD10: "B24", tariffCode: "0190", patientGender: "M", patientAge: 35, amount: 480, dateOfService: "2026-03-10" },
    schemeCode: "MH",
    expectedOutcome: "rejected_pmb_missed",
    reason: "B24 (unspecified HIV disease) when patient has confirmed HIV. B20.x is more specific PMB code — better for CDL chronic benefits.",
    fix: "Change to B20.0-B20.9 based on manifestation for more specific PMB coding and CDL registration.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.08,
  },
  {
    id: 72,
    claim: { lineNumber: 1, primaryICD10: "Z03.9", tariffCode: "0190", patientGender: "F", patientAge: 50, amount: 520, dateOfService: "2026-03-09" },
    schemeCode: "DH",
    expectedOutcome: "rejected_pmb_missed",
    reason: "Z03.9 (observation for suspected disease) when patient had confirmed breast lump. If C50.x is confirmed, it is PMB oncology.",
    fix: "If malignancy confirmed, change to C50.x for PMB oncology programme registration and guaranteed cover.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 73,
    claim: { lineNumber: 1, primaryICD10: "R00.0", tariffCode: "0190", patientGender: "M", patientAge: 65, amount: 430, dateOfService: "2026-03-08" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_pmb_missed",
    reason: "R00.0 (tachycardia, unspecified) when patient has confirmed heart failure. I50.x is PMB/CDL with much better benefits.",
    fix: "If heart failure is confirmed, change to I50.0/I50.1/I50.9 for CDL and PMB benefits.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 74,
    claim: { lineNumber: 1, primaryICD10: "M15.9", tariffCode: "0190", patientGender: "F", patientAge: 60, amount: 470, dateOfService: "2026-03-07" },
    schemeCode: "BON",
    expectedOutcome: "rejected_pmb_missed",
    reason: "M15.9 (polyosteoarthritis) when patient has confirmed RA. M05.x/M06.x is CDL — chronic medication benefits.",
    fix: "If rheumatoid arthritis is confirmed, change to M05.x (seropositive) or M06.x (seronegative) for CDL registration.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 75,
    claim: { lineNumber: 1, primaryICD10: "E78.0", tariffCode: "0190", patientGender: "M", patientAge: 52, amount: 500, dateOfService: "2026-03-06" },
    schemeCode: "BM",
    expectedOutcome: "rejected_pmb_missed",
    reason: "E78.0 (hypercholesterolaemia) coded but patient is actually on treatment for coronary artery disease. I25.x is PMB for CAD.",
    fix: "If CAD is diagnosed, use I25.1 (atherosclerotic heart disease) as primary. E78.0 can be secondary. PMB coverage for CAD.",
    severity: "warning",
    category: "pmb_missed",
    rejectionProbability: 0.08,
  },

  // ═══════════════════════════════════════════════════════════════
  // CDL OPPORTUNITIES MISSED (10 examples)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 76,
    claim: { lineNumber: 1, primaryICD10: "R73.9", tariffCode: "0190", patientGender: "M", patientAge: 50, nappiCode: "714627001", amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on metformin (NAPPI 714627001) but coded R73.9 (hyperglycaemia). If diagnosed Type 2 DM, E11.x is CDL — chronic benefits.",
    fix: "If diabetes is confirmed, change to E11.9 and submit CDL application. Chronic benefits will cover medication long-term.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 77,
    claim: { lineNumber: 1, primaryICD10: "R00.0", tariffCode: "0190", patientGender: "F", patientAge: 55, nappiCode: "745312001", amount: 430, dateOfService: "2026-03-14" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on atenolol (beta-blocker) coded R00.0. If hypertension is diagnosed, I10.x is CDL — chronic medication benefits.",
    fix: "If hypertension confirmed, change to I10.0 and submit CDL application. GEMS chronic benefits cover anti-hypertensives.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 78,
    claim: { lineNumber: 1, primaryICD10: "J98.0", tariffCode: "0190", patientGender: "M", patientAge: 65, nappiCode: "756891001", amount: 470, dateOfService: "2026-03-13" },
    schemeCode: "BON",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on tiotropium bromide coded J98.0 (bronchial disease). If COPD diagnosed, J44.x is CDL with chronic benefits.",
    fix: "If COPD confirmed, change to J44.9 and submit CDL application. Bonitas chronic benefits cover COPD inhalers.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 79,
    claim: { lineNumber: 1, primaryICD10: "R25.2", tariffCode: "0190", patientGender: "F", patientAge: 28, nappiCode: "745891001", amount: 520, dateOfService: "2026-03-12" },
    schemeCode: "DH",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on valproate coded R25.2 (cramp/spasm). If epilepsy diagnosed, G40.x is CDL — chronic medication cover.",
    fix: "If epilepsy confirmed, change to G40.x and register for CDL. Chronic benefits cover anti-epileptic medication.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 80,
    claim: { lineNumber: 1, primaryICD10: "R63.4", tariffCode: "0190", patientGender: "F", patientAge: 48, nappiCode: "706712001", amount: 430, dateOfService: "2026-03-11" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on levothyroxine coded R63.4 (abnormal weight loss). If hypothyroidism confirmed, E03.x is CDL condition.",
    fix: "If hypothyroidism confirmed, change to E03.9 and submit CDL application. GEMS chronic benefits cover thyroid medication.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 81,
    claim: { lineNumber: 1, primaryICD10: "F41.9", tariffCode: "0190", patientGender: "M", patientAge: 35, nappiCode: "789234001", amount: 480, dateOfService: "2026-03-10" },
    schemeCode: "MH",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on SSRI coded F41.9 (anxiety disorder). If major depression diagnosed, F32.x/F33.x is CDL — chronic benefits.",
    fix: "If depression confirmed, change to F32.x (single episode) or F33.x (recurrent) for CDL chronic medication benefits.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.10,
  },
  {
    id: 82,
    claim: { lineNumber: 1, primaryICD10: "M79.1", tariffCode: "0190", patientGender: "F", patientAge: 45, nappiCode: "823456001", amount: 520, dateOfService: "2026-03-09" },
    schemeCode: "DH",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on methotrexate coded M79.1 (myalgia). If RA confirmed, M05.x/M06.x is CDL — covers biologics and DMARDs.",
    fix: "If RA confirmed, change to M05.x or M06.x and register for CDL. CDL benefits cover expensive RA medications.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 83,
    claim: { lineNumber: 1, primaryICD10: "G25.0", tariffCode: "0190", patientGender: "M", patientAge: 70, nappiCode: "867543001", amount: 430, dateOfService: "2026-03-08" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on levodopa coded G25.0 (essential tremor). If Parkinson's diagnosed, G20 is CDL — chronic benefits cover PD meds.",
    fix: "If Parkinson's confirmed, change to G20 and submit CDL application for chronic medication benefits.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 84,
    claim: { lineNumber: 1, primaryICD10: "N28.9", tariffCode: "0190", patientGender: "F", patientAge: 62, amount: 470, dateOfService: "2026-03-07" },
    schemeCode: "BON",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient with Stage 3 CKD coded N28.9 (kidney disorder NOS). N18.3 is CDL condition — chronic benefits and potential PMB.",
    fix: "If CKD confirmed with eGFR staging, change to N18.3 (CKD stage 3) and register for CDL.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.12,
  },
  {
    id: 85,
    claim: { lineNumber: 1, primaryICD10: "K52.9", tariffCode: "0190", patientGender: "M", patientAge: 28, nappiCode: "891234001", amount: 500, dateOfService: "2026-03-06" },
    schemeCode: "BM",
    expectedOutcome: "rejected_cdl_missed",
    reason: "Patient on mesalazine coded K52.9 (non-infective colitis). If ulcerative colitis confirmed, K51.x is CDL condition.",
    fix: "If UC confirmed, change to K51.0 or K51.9 and submit CDL application for chronic medication benefits.",
    severity: "warning",
    category: "cdl_missed",
    rejectionProbability: 0.10,
  },

  // ═══════════════════════════════════════════════════════════════
  // TARIFF UNBUNDLING VIOLATIONS (15 examples)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 86,
    claim: { lineNumber: 1, primaryICD10: "S52.50", secondaryICD10: ["W19.9"], tariffCode: "0196", patientGender: "M", patientAge: 35, amount: 850, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_unbundling",
    reason: "Wound exploration (0196) billed separately alongside wound closure (0198) and debridement (0197). Comprehensive wound repair tariff (0195) covers all three.",
    fix: "Use comprehensive tariff 0195 instead of billing 0196 + 0197 + 0198 separately. Single fee covers full procedure.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.85,
  },
  {
    id: 87,
    claim: { lineNumber: 1, primaryICD10: "J06.9", tariffCode: "0190", patientGender: "F", patientAge: 34, amount: 520, dateOfService: "2026-03-15" },
    schemeCode: "DH",
    expectedOutcome: "rejected_unbundling",
    reason: "Consultation (0190) billed separately on same day as comprehensive assessment (0100). Consultation is included in assessment tariff.",
    fix: "Bill only the comprehensive assessment (0100). Do not add a separate consultation (0190) on the same day.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.88,
  },
  {
    id: 88,
    claim: { lineNumber: 1, primaryICD10: "M54.5", tariffCode: "0190", patientGender: "M", patientAge: 45, amount: 520, dateOfService: "2026-03-14" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_unbundling",
    reason: "GP consultation billed with separate physiotherapy assessment on same day for same condition. Follow-up physio assessment is bundled with initial consultation.",
    fix: "Bill GP consultation only. If physio referral, physiotherapist bills their own initial assessment separately on a different date.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.80,
  },
  {
    id: 89,
    claim: { lineNumber: 1, primaryICD10: "K35.8", tariffCode: "0190", patientGender: "M", patientAge: 22, amount: 4500, dateOfService: "2026-03-13" },
    schemeCode: "BON",
    expectedOutcome: "rejected_unbundling",
    reason: "Pre-operative consultation, anaesthetic assessment, and surgical consultation all billed separately on same day for appendectomy. Pre-op is bundled with surgical tariff.",
    fix: "Pre-op assessment is included in the surgical tariff. Only bill surgical fee plus anaesthetic fee (separate practitioner).",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.82,
  },
  {
    id: 90,
    claim: { lineNumber: 1, primaryICD10: "Z01.0", tariffCode: "0190", patientGender: "F", patientAge: 40, amount: 1200, dateOfService: "2026-03-12" },
    schemeCode: "MH",
    expectedOutcome: "rejected_unbundling",
    reason: "Eye examination (0190) billed alongside visual field testing and tonometry separately. Comprehensive ophthalmology assessment includes all tests.",
    fix: "Bill comprehensive ophthalmology assessment. Individual tests are bundled into the assessment tariff.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.78,
  },
  {
    id: 91,
    claim: { lineNumber: 1, primaryICD10: "I10.0", tariffCode: "0190", patientGender: "M", patientAge: 55, amount: 800, dateOfService: "2026-03-11" },
    schemeCode: "MS",
    expectedOutcome: "rejected_unbundling",
    reason: "GP consultation (0190) billed alongside ECG reading (separate code) and blood pressure check. ECG reading and BP are part of the consultation.",
    fix: "BP measurement is always included in consultation. ECG reading should only be billed if a 12-lead ECG was performed.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.75,
  },
  {
    id: 92,
    claim: { lineNumber: 1, primaryICD10: "L70.0", tariffCode: "0190", patientGender: "F", patientAge: 16, amount: 1500, dateOfService: "2026-03-10" },
    schemeCode: "DH",
    expectedOutcome: "rejected_unbundling",
    reason: "Dermatology consultation billed with separate skin biopsy punch (0196), specimen collection (0197), and pathology request. Biopsy punch is a single procedure — no separate collection fee.",
    fix: "Bill dermatology consultation + biopsy procedure (single tariff). Specimen handling is included. Pathology is billed by the lab separately.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.82,
  },
  {
    id: 93,
    claim: { lineNumber: 1, primaryICD10: "H25.1", tariffCode: "0190", patientGender: "F", patientAge: 72, amount: 18000, dateOfService: "2026-03-09" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_unbundling",
    reason: "Cataract surgery (phacoemulsification) billed with separate lens insertion, separate anterior vitrectomy, and separate wound closure. All are included in the comprehensive cataract tariff.",
    fix: "Bill the comprehensive cataract surgery tariff. Phaco, IOL insertion, and wound closure are bundled.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.90,
  },
  {
    id: 94,
    claim: { lineNumber: 1, primaryICD10: "K80.1", tariffCode: "0190", patientGender: "F", patientAge: 48, amount: 12000, dateOfService: "2026-03-08" },
    schemeCode: "BON",
    expectedOutcome: "rejected_unbundling",
    reason: "Laparoscopic cholecystectomy billed with separate trocar insertion (x4), separate camera insertion, and separate specimen retrieval. All are components of the laparoscopic procedure.",
    fix: "Bill laparoscopic cholecystectomy as a single comprehensive tariff. Port insertion, camera use, and specimen retrieval are inherent to the procedure.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.88,
  },
  {
    id: 95,
    claim: { lineNumber: 1, primaryICD10: "O80.0", tariffCode: "0190", patientGender: "F", patientAge: 29, amount: 8000, dateOfService: "2026-03-07" },
    schemeCode: "MH",
    expectedOutcome: "rejected_unbundling",
    reason: "Normal vaginal delivery billed with separate episiotomy repair, perineal suturing, and cord clamping. All included in normal delivery tariff.",
    fix: "Bill normal delivery tariff only. Episiotomy, repair, and cord management are bundled unless complications arise.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.85,
  },
  {
    id: 96,
    claim: { lineNumber: 1, primaryICD10: "K35.8", tariffCode: "0190", patientGender: "M", patientAge: 30, amount: 2500, dateOfService: "2026-03-15" },
    schemeCode: "BM",
    expectedOutcome: "rejected_unbundling",
    reason: "Anaesthetic billed with separate intubation, monitoring, and recovery room supervision. All are components of anaesthetic management.",
    fix: "Bill comprehensive anaesthetic tariff based on time and complexity. Intubation, monitoring, and recovery are included.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.80,
  },
  {
    id: 97,
    claim: { lineNumber: 1, primaryICD10: "M17.1", tariffCode: "0186", patientGender: "M", patientAge: 58, amount: 22000, dateOfService: "2026-03-14" },
    schemeCode: "DH",
    expectedOutcome: "rejected_unbundling",
    reason: "Knee arthroscopy billed with separate diagnostic arthroscopy and separate meniscal debridement. If both are done, bill the more comprehensive therapeutic procedure only.",
    fix: "Bill therapeutic arthroscopy (meniscal debridement) only. Diagnostic arthroscopy is included in the therapeutic tariff.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.85,
  },
  {
    id: 98,
    claim: { lineNumber: 1, primaryICD10: "J18.9", tariffCode: "0190", patientGender: "M", patientAge: 67, amount: 3500, dateOfService: "2026-03-13" },
    schemeCode: "GEMS",
    expectedOutcome: "rejected_unbundling",
    reason: "Hospital admission consultation billed with separate admission examination and separate treatment plan. All are part of the admission consultation tariff.",
    fix: "Bill admission consultation tariff only. The examination and initial treatment plan are inherent to the admission consultation.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.82,
  },
  {
    id: 99,
    claim: { lineNumber: 1, primaryICD10: "Z30.0", tariffCode: "0190", patientGender: "F", patientAge: 32, amount: 2800, dateOfService: "2026-03-12" },
    schemeCode: "MH",
    expectedOutcome: "rejected_unbundling",
    reason: "IUD insertion billed with separate cervical dilation, separate device insertion, and separate sonographic guidance. All bundled in IUD insertion tariff.",
    fix: "Bill IUD insertion as comprehensive procedure. Cervical prep, insertion, and ultrasound guidance (if used) are bundled.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.78,
  },
  {
    id: 100,
    claim: { lineNumber: 1, primaryICD10: "S82.10", secondaryICD10: ["W19.9"], tariffCode: "0196", patientGender: "M", patientAge: 40, amount: 15000, dateOfService: "2026-03-11" },
    schemeCode: "BON",
    expectedOutcome: "rejected_unbundling",
    reason: "Open reduction internal fixation (ORIF) of tibia billed with separate plate application, separate screw insertion (x6), and separate wound closure. All are components of the ORIF tariff.",
    fix: "Bill ORIF as a single comprehensive tariff. Plate, screws, and closure are inherent to the fixation procedure.",
    severity: "error",
    category: "unbundling",
    rejectionProbability: 0.88,
  },
];

// ─── DATASET BUILDER ────────────────────────────────────────────

function buildOutcomeDistribution(): Record<string, number> {
  const dist: Record<string, number> = {};
  for (const ex of TRAINING_EXAMPLES) {
    dist[ex.expectedOutcome] = (dist[ex.expectedOutcome] || 0) + 1;
  }
  return dist;
}

// ─── EXPORTS ────────────────────────────────────────────────────

/** Get the full training dataset */
export function getTrainingDataset(): TrainingDataset {
  return {
    version: "1.0.0",
    generatedAt: "2026-03-20",
    totalExamples: TRAINING_EXAMPLES.length,
    outcomeDistribution: buildOutcomeDistribution(),
    examples: TRAINING_EXAMPLES,
  };
}

/** Get training examples by outcome type */
export function getExamplesByOutcome(outcome: TrainingOutcome): TrainingExample[] {
  return TRAINING_EXAMPLES.filter(e => e.expectedOutcome === outcome);
}

/** Get training examples by scheme */
export function getExamplesByScheme(schemeCode: string): TrainingExample[] {
  const upper = schemeCode.toUpperCase().trim();
  return TRAINING_EXAMPLES.filter(e => e.schemeCode === upper);
}

/** Get training examples by category */
export function getExamplesByCategory(category: string): TrainingExample[] {
  return TRAINING_EXAMPLES.filter(e => e.category === category);
}

/** Get only examples that should be rejected (for negative training) */
export function getRejectedExamples(): TrainingExample[] {
  return TRAINING_EXAMPLES.filter(e => e.expectedOutcome !== "accepted");
}

/** Get only valid examples (for positive training) */
export function getAcceptedExamples(): TrainingExample[] {
  return TRAINING_EXAMPLES.filter(e => e.expectedOutcome === "accepted");
}

/** Get all training examples (raw array) */
export function getAllTrainingExamples(): TrainingExample[] {
  return TRAINING_EXAMPLES;
}

/** Convert training examples to a format suitable for ML model fine-tuning */
export function toFineTuningFormat(): Array<{
  input: string;
  output: string;
  metadata: { id: number; scheme: string; category: string };
}> {
  return TRAINING_EXAMPLES.map(ex => ({
    input: JSON.stringify({
      icd10: ex.claim.primaryICD10,
      secondaryICD10: ex.claim.secondaryICD10 || [],
      tariff: ex.claim.tariffCode || "",
      nappi: ex.claim.nappiCode || "",
      gender: ex.claim.patientGender || "U",
      age: ex.claim.patientAge || 0,
      amount: ex.claim.amount || 0,
      scheme: ex.schemeCode,
    }),
    output: JSON.stringify({
      outcome: ex.expectedOutcome,
      rejectionProbability: ex.rejectionProbability,
      reason: ex.reason,
      fix: ex.fix,
    }),
    metadata: {
      id: ex.id,
      scheme: ex.schemeCode,
      category: ex.category,
    },
  }));
}
