"use client";

import { useEffect, useState } from "react";
import type { SOAPNote, ICD10Suggestion } from "@/lib/scribe/types";

interface PrintData {
  soap: SOAPNote;
  transcript: string;
  icd10Codes: ICD10Suggestion[];
  patientName: string;
  date: string;
}

export default function ScribePrintPage() {
  const [data, setData] = useState<PrintData | null>(null);

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("scribe-print-data");
      if (raw) {
        setData(JSON.parse(raw));
        setTimeout(() => window.print(), 500);
      }
    } catch { /* ignore */ }
  }, []);

  if (!data) {
    return (
      <div style={{ padding: 40, fontFamily: "system-ui" }}>
        <h1>No scribe data found</h1>
        <p>Please export from the AI Scribe page first.</p>
      </div>
    );
  }

  const { soap, transcript, icd10Codes, patientName, date } = data;
  const formattedDate = new Date(date).toLocaleDateString("en-ZA", {
    year: "numeric", month: "long", day: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  return (
    <>
      <style>{`
        @media print { .no-print { display: none !important; } body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
        body { margin: 0; background: white; color: #1a1a1a; font-family: system-ui, -apple-system, sans-serif; }
        .page { max-width: 800px; margin: 0 auto; padding: 40px; }
        .header { border-bottom: 2px solid #0d9488; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { font-size: 20px; color: #0d9488; margin: 0 0 4px; }
        .header p { font-size: 12px; color: #666; margin: 0; }
        .meta { display: flex; gap: 24px; margin-bottom: 24px; font-size: 13px; }
        .meta-item { display: flex; flex-direction: column; }
        .meta-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #999; margin-bottom: 2px; }
        .soap-section { margin-bottom: 20px; border-left: 3px solid; padding-left: 16px; }
        .soap-s { border-color: #f59e0b; }
        .soap-o { border-color: #3b82f6; }
        .soap-a { border-color: #8b5cf6; }
        .soap-p { border-color: #22c55e; }
        .soap-title { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; }
        .soap-content { font-size: 13px; color: #374151; line-height: 1.6; white-space: pre-wrap; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 14px; font-weight: 600; color: #0d9488; border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; margin-bottom: 10px; }
        .code-row { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid #f3f4f6; font-size: 12px; }
        .code-label { font-weight: 600; color: #0d9488; font-family: monospace; }
        .transcript { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 14px; font-size: 12px; line-height: 1.6; color: #4b5563; white-space: pre-wrap; max-height: 300px; overflow: hidden; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 10px; color: #9ca3af; text-align: center; }
        .print-btn { position: fixed; top: 16px; right: 16px; padding: 8px 20px; background: #0d9488; color: white; border: none; border-radius: 8px; font-size: 13px; font-weight: 600; cursor: pointer; }
      `}</style>

      <button className="print-btn no-print" onClick={() => window.print()}>Print / Save PDF</button>

      <div className="page">
        <div className="header">
          <h1>SOAP Clinical Note</h1>
          <p>AI Clinical Scribe — Netcare Health OS</p>
        </div>

        <div className="meta">
          <div className="meta-item"><span className="meta-label">Patient</span><span>{patientName}</span></div>
          <div className="meta-item"><span className="meta-label">Date</span><span>{formattedDate}</span></div>
          <div className="meta-item"><span className="meta-label">Generated By</span><span>AI Clinical Scribe</span></div>
        </div>

        <div className="soap-section soap-s">
          <div className="soap-title" style={{ color: "#f59e0b" }}>S - Subjective</div>
          <div className="soap-content">{soap.subjective || "Not documented"}</div>
        </div>

        <div className="soap-section soap-o">
          <div className="soap-title" style={{ color: "#3b82f6" }}>O - Objective</div>
          <div className="soap-content">{soap.objective || "Not documented"}</div>
        </div>

        <div className="soap-section soap-a">
          <div className="soap-title" style={{ color: "#8b5cf6" }}>A - Assessment</div>
          <div className="soap-content">{soap.assessment || "Not documented"}</div>
        </div>

        <div className="soap-section soap-p">
          <div className="soap-title" style={{ color: "#22c55e" }}>P - Plan</div>
          <div className="soap-content">{soap.plan || "Not documented"}</div>
        </div>

        {icd10Codes.length > 0 && (
          <div className="section">
            <div className="section-title">ICD-10 Codes (WHO)</div>
            {icd10Codes.map((c, i) => (
              <div key={i} className="code-row">
                <span><span className="code-label">{c.code}</span> {c.description}</span>
                <span style={{ color: "#9ca3af" }}>{c.confidence}%</span>
              </div>
            ))}
          </div>
        )}

        <div className="section">
          <div className="section-title">Full Transcript</div>
          <div className="transcript">{transcript}</div>
        </div>

        <div className="footer">
          Generated by Netcare Health OS AI Clinical Scribe — {formattedDate}
          <br />This is an AI-generated document. Clinical review required before any treatment decisions.
        </div>
      </div>
    </>
  );
}
